import { db } from "@workspace/db";
import { experiencesTable } from "@workspace/db/schema";
import { eq } from "drizzle-orm";

const ENRICHED: {
  id: number;
  descriptionEn: string;
  descriptionAr: string;
  menuDetailsEn: string;
  menuDetailsAr: string;
  rulesEn: string;
  rulesAr: string;
}[] = [
  {
    id: 1,
    descriptionEn: `Step into the world of ultra-premium dining with an intimate six-course wagyu dinner prepared entirely tableside by Chef Hassan Al-Zahrani, one of Riyadh's most celebrated culinary talents. This exclusive experience is limited to just eight guests, ensuring every dish receives the personal attention it deserves.

The evening unfolds with a champagne welcome reception, followed by a progressive menu built around A5 Japanese wagyu sourced directly from Kagoshima prefecture — arguably the finest beef on earth. Chef Al-Zahrani showcases the full spectrum of wagyu preparation: raw carpaccio with aged balsamic, seared tataki with ponzu, and the centrepiece slow-roasted striploin carved tableside over live flame. Each course is accompanied by truffle accompaniments flown in from Périgord, and a personally curated sake pairing selected by the chef himself.

The finale — a warm dark chocolate fondant with wagyu tallow caramel — cements what will undoubtedly be a memory you return to long after the plates are cleared.`,
    descriptionAr: `انغمس في عالم المطبخ الراقي الاستثنائي مع عشاء واغيو حميم من ستة أطباق يُحضَّر على الطاولة بالكامل بواسطة الشيف حسن الزهراني، أحد أبرز المواهب الطهوية في الرياض. تقتصر هذه التجربة الحصرية على ثمانية ضيوف فقط، مما يضمن أن كل طبق يحظى بالاهتمام الشخصي الذي يستحقه.

تبدأ الأمسية باستقبال بالشمبانيا، ثم تتتالى قائمة من الأطباق المتدرجة المبنية على واغيو ياباني A5 مُستورد مباشرة من مقاطعة كاغوشيما — أرفع لحوم البقر في العالم. يستعرض الشيف الزهراني طيفاً كاملاً من طرق تحضير الواغيو: كاربتشيو نيء بالخل البلسمي المعتق، وتاتاكي محمر بصلصة البونزو، وشريحة الستريبلوين المشوية ببطء والمقطّعة على الطاولة فوق لهب حي. كل طبق مصحوب بمرافقات الكمأ المستوردة من بيريغور ومقترن بساكي منتقى بعناية من قِبل الشيف نفسه.

الختام — فوندان الشوكولاتة الداكنة الدافئ مع كراميل دهن الواغيو — يُرسّخ ليلة لا تُنسى تظل في الذاكرة طويلاً بعد انتهاء الوليمة.`,
    menuDetailsEn: `Welcome Reception: Japanese A5 wagyu crudo, shaved truffle, aged balsamic reduction, gold leaf\nCourse 1: Wagyu bone marrow toast, Périgord truffle butter, sea salt flakes\nCourse 2: Wagyu tataki, ponzu gelée, pickled daikon, micro shiso\nCourse 3: A5 wagyu carpaccio, 36-month parmigiano, rocket, white truffle oil\nCourse 4: Slow-roasted wagyu striploin, carved tableside, sauce bordelaise, pomme purée\nCourse 5: Wagyu short rib, red wine jus, roasted bone marrow, seasonal vegetables\nDessert: Dark chocolate fondant, wagyu tallow caramel, yuzu sorbet\nSake Pairing: 4 curated pours from Dassai, Kubota, and Hakkaisan`,
    menuDetailsAr: `استقبال: كرودو واغيو A5 ياباني، كمأ مبشور، تخفيض بلسمي معتق، ورق ذهب\nطبق 1: توست نخاع الواغيو، زبدة كمأ بيريغور، رقائق ملح البحر\nطبق 2: تاتاكي واغيو، جيلي البونزو، فجل مخلل، شيسو صغير\nطبق 3: كاربتشيو واغيو A5، بارميجيانو 36 شهراً، جرجير، زيت كمأ أبيض\nطبق 4: ستريبلوين واغيو مشوي ببطء، يُقطَّع على الطاولة، صلصة بوردليز، بوريه البطاطا\nطبق 5: ضلع واغيو قصير، مرق نبيذ أحمر، نخاع محمص، خضروات موسمية\nحلوى: فوندان شوكولاتة داكنة، كراميل دهن الواغيو، سوربيه يوزو\nإقران الساكي: 4 جرعات منتقاة من داساي وكوبوتا وهاكاييسان`,
    rulesEn: `Minimum age: 18 years. Alcoholic beverages not served — premium sake pairing is halal-certified. Full payment required at booking. Cancellations accepted up to 72 hours before; 50% refund within 48 hours; no refund within 24 hours. Dietary requirements (vegetarian, gluten-free, nut-free) must be noted at booking. Smart casual dress code required. Photography welcome during setup; chef requests no filming during service. Maximum 8 guests per session.`,
    rulesAr: `الحد الأدنى للعمر: 18 سنة. لا تُقدَّم مشروبات كحولية — إقران الساكي مُعتمد حلالاً. يُشترط الدفع الكامل عند الحجز. يُقبل الإلغاء حتى 72 ساعة قبل الموعد؛ استرداد 50% خلال 48 ساعة؛ لا استرداد خلال 24 ساعة. يجب الإشارة إلى متطلبات النظام الغذائي (نباتي، خالٍ من الغلوتين، خالٍ من المكسرات) عند الحجز. اللباس شبه رسمي مطلوب. التصوير مسموح خلال الإعداد؛ يطلب الشيف عدم التصوير خلال الخدمة. الحد الأقصى 8 ضيوف لكل جلسة.`,
  },
  {
    id: 2,
    descriptionEn: `Discover the meditative art of omakase — "I leave it to you" — under the guidance of Chef Kenji Tanaka, whose decade of training in Osaka and Tokyo has shaped one of the most technically precise sushi programmes in Saudi Arabia. This two-hour masterclass is designed for serious food lovers who want to move beyond eating sushi to understanding it.

The session begins with an introduction to Japanese knife craft, where you learn the geometry of fish breakdown — from whole yellowfin tuna to perfectly portioned nigiri cuts. You will master the three essential rice techniques: temperature calibration, vinegar seasoning ratios, and the precise hand-pressure method that keeps each grain intact while ensuring the bite dissolves perfectly. Over twelve nigiri pieces, you will build fluency with tamago, hamachi, salmon, bluefin, and uni, guided by Chef Kenji's quiet corrections and encouragement.

The masterclass concludes with a sake tasting flight of three premium selections paired with the sushi you have made. Each guest departs with a recipe card, a custom bamboo rice paddle, and — most importantly — the knowledge to bring omakase quality into their own kitchen.`,
    descriptionAr: `اكتشف الفن التأملي للأوماكاسي — "أُفوّض إليك الأمر" — تحت إشراف الشيف كينجي تاناكا، الذي شكّل عقد من التدريب في أوساكا وطوكيو أحد أدق برامج السوشي الحرفية في المملكة العربية السعودية. صُمّمت هذه الدورة الاحترافية التي تمتد لساعتين لعشّاق الطعام الجادين الراغبين في تجاوز تناول السوشي إلى فهمه العميق.

تبدأ الجلسة بمقدمة في فن سكاكين اليابانية وهندسة تقطيع السمك — من تونة الزعفان الكاملة إلى قطع النيغيري المتقنة. ستتقن ثلاث تقنيات أرز أساسية: معايرة درجة الحرارة، ونسب توابل الخل، وطريقة ضغط اليد الدقيقة التي تحافظ على كل حبة سليمة مع ضمان ذوبان كل قضمة بالتوازن المثالي. عبر اثنتي عشرة قطعة نيغيري، ستبني إلماماً بالتاماغو والهاماتشي والسلمون والتونة الزرقاء والأوني، بتوجيه من الشيف كينجي.

تختتم الدورة بتذوق ثلاثة اختيارات من الساكي الفاخر مقترنة بالسوشي الذي صنعته بيدك. يغادر كل ضيف حاملاً بطاقة الوصفة ومجرفة أرز خيزرانية مخصصة، والأهم — المعرفة التي تتيح جودة الأوماكاسي في مطبخه الخاص.`,
    menuDetailsEn: `Welcome: Chilled hojicha tea and Japanese pickles\nLesson 1: Knife skills — deboning, filleting, slicing (yellowfin tuna)\nLesson 2: Sushi rice preparation — vinegar seasoning, temperature, texture\nLesson 3: Nigiri moulding technique — 12 pieces total across 6 varieties\nVarieties: Tamago (egg), Hamachi (yellowtail), Sake (salmon), Hon-maguro (bluefin), Uni (sea urchin), Ebi (prawn)\nGarnishes: Wasabi, pickled ginger, micro shiso, yuzu kosho\nSake Pairing: Three premium cups — Junmai, Ginjo, Daiginjo\nTake-home: Recipe card, bamboo rice paddle`,
    menuDetailsAr: `ترحيب: شاي هوجيتشا بارد ومخللات يابانية\nدرس 1: مهارات السكاكين — تنظيف العظام، التشريح، التقطيع (تونة الزعفان)\nدرس 2: تحضير أرز السوشي — توابل الخل، درجة الحرارة، القوام\nدرس 3: تقنية تشكيل النيغيري — 12 قطعة موزعة على 6 أصناف\nالأصناف: تاماغو (بيض)، هاماتشي (ذيل أصفر)، ساكي (سلمون)، هون-ماغورو (تونة زرقاء)، أوني (قنفذ بحر)، ايبي (روبيان)\nإضافات: واسابي، زنجبيل مخلل، شيسو صغير، يوزو كوشو\nإقران الساكي: ثلاثة أكواب فاخرة — جونماي وجينجو وداي-جينجو\nما تأخذه: بطاقة وصفة ومجرفة أرز خيزرانية`,
    rulesEn: `Minimum age: 16 years. Non-alcoholic sake alternatives available on request — please notify at booking. Full payment due at reservation. Free cancellation up to 48 hours before; 50% refund within 24 hours; no refund on same day. Shellfish and seafood allergies cannot be accommodated. Comfortable clothing recommended; aprons and gloves provided. Maximum 8 guests per class.`,
    rulesAr: `الحد الأدنى للعمر: 16 سنة. بدائل الساكي غير الكحولية متاحة عند الطلب — يُرجى الإخطار عند الحجز. الدفع الكامل مطلوب عند الحجز. إلغاء مجاني حتى 48 ساعة قبل الموعد؛ استرداد 50% خلال 24 ساعة؛ لا استرداد في نفس اليوم. لا يمكن استيعاب حساسية القشريات والمأكولات البحرية. ملابس مريحة موصى بها؛ مريلة وقفازات مُقدَّمة. الحد الأقصى 8 ضيوف لكل فصل.`,
  },
  {
    id: 3,
    descriptionEn: `Beneath the oldest skies on earth, the ancient rock city of AlUla becomes a breathtaking open-air dining room. This ethereal starlight dinner takes place among the sandstone formations of Dadan, where the silence is so absolute you can hear the desert breathe. Torchlight paths lead guests to a private table set with hand-embroidered linen, candles, and a centrepiece of dried desert wildflowers.

Chef Rawan Alharbi has crafted a six-course menu that tells the culinary story of the Lihyanite kingdom that once flourished here — dishes rooted in ancient spice trade routes, featuring flavours of saffron, dried rose, wild thyme, and caravan-era preserved meats. The signature course is her legendary slow-cooked leg of lamb, marinated for 24 hours in a blend of Nabataean spices, buried in hot sand through the afternoon, and served with fragrant saffron rice studded with raisins and pine nuts.

An astronomer from the local heritage authority joins for the second half of dinner, narrating the star-lore of the Arabian Peninsula while a traditional oud player performs softly in the distance. This is not just a meal — it is a passage through time.`,
    descriptionAr: `تحت أقدم سماوات الأرض، تتحوّل مدينة العُلا الصخرية القديمة إلى قاعة طعام مفتوحة مذهلة. يُقام هذا العشاء الأثيري تحت ضوء النجوم وسط تشكيلات الحجر الرملي في ددان، حيث الصمت مطبق لدرجة أنك تسمع أنفاس الصحراء. مسالك المشاعل تقود الضيوف إلى طاولة خاصة مزيّنة بكتان مطرز يدوياً وشموع وتحفة وسطية من زهور الصحراء البرية المجففة.

ابتكرت الشيفة روان الحربي قائمة من ستة أطباق تروي القصة الطهوية لمملكة اللحيانيين التي ازدهرت هنا يوماً — أطباق متجذرة في طرق تجارة البهارات القديمة، تتضمن نكهات الزعفران والورد المجفف والزعتر البري واللحوم المحفوظة من عصور القوافل. الطبق المميز هو ساقها الشهيرة من الضأن المطهو ببطء، مُتبَّلة لـ 24 ساعة بخليط من البهارات النبطية، ومدفونة في الرمل الساخن طوال الظهيرة، وتُقدَّم مع أرز زعفراني عطري مُحشى بالزبيب والصنوبر.

ينضم فلكي من هيئة التراث المحلية في النصف الثاني من العشاء، يروي أساطير النجوم في شبه الجزيرة العربية بينما يعزف عازف عود تقليدي بهدوء في الأفق. هذه ليست وجبة فحسب — إنها عبور عبر الزمن.`,
    menuDetailsEn: `Arrival: Dried rose & cardamom qahwa, Medjool dates, camel milk labneh with wild thyme\nCourse 1: Lihyanite spiced lentil soup, smoked cumin, desert herb croutons\nCourse 2: Camel carpaccio, pomegranate molasses, rocket, candied rose petals\nCourse 3: Slow-cooked leg of lamb (sand-buried 4 hours), Nabataean spice blend, saffron rice with raisins and pine nuts\nCourse 4: Roasted quail, dried apricot jus, caravan-spiced couscous\nCourse 5: Arabian cheese board — camel milk labneh, aged goat, dried figs, honey\nDessert: Saffron panna cotta, rose syrup, pistachio crumble\nBeverages: Arabic coffee, hibiscus tea, desert herb infusions throughout`,
    menuDetailsAr: `الوصول: قهوة الورد والهيل، تمر مجدول، لبنة حليب الإبل بالزعتر البري\nطبق 1: شوربة عدس لحيانية متبلة، كمون مدخن، قطع خبز أعشاب صحراوية\nطبق 2: كاربتشيو الإبل، دبس رمان، جرجير، بتلات ورد مُسكَّرة\nطبق 3: ساق ضأن مطهوة ببطء (مدفونة في الرمل 4 ساعات)، خلطة بهارات نبطية، أرز زعفراني بالزبيب والصنوبر\nطبق 4: سمان محمص، مرق مشمش مجفف، كسكس متبّل بتوابل القوافل\nطبق 5: لوح جبن عربي — لبنة حليب الإبل، معز معتق، تين مجفف، عسل\nحلوى: بانا كوتا زعفران، شراب ورد، فتات فستق\nمشروبات: قهوة عربية وشاي الكركديه وإضافات أعشاب صحراوية طوال الجلسة`,
    rulesEn: `Minimum age: 12 years (children under 12 not suitable for late-night desert terrain). Location accessible only by 4WD vehicle; transportation from AlUla city centre included. Warm layers strongly recommended — desert nights reach 8°C in winter. No stiletto heels; flat or desert-boot footwear required. Full payment at booking. Free cancellation 5 days before; 50% refund within 72 hours; no refund within 48 hours. Weather-dependent: postponement offered if sandstorm conditions arise.`,
    rulesAr: `الحد الأدنى للعمر: 12 سنة (الأطفال دون 12 سنة غير مناسبين للتضاريس الصحراوية الليلية). الموقع لا يمكن الوصول إليه إلا بسيارة دفع رباعي؛ يشمل النقل من وسط مدينة العُلا. طبقات الملابس الدافئة موصى بها بشدة — تنخفض درجات حرارة الصحراء ليلاً إلى 8°C في الشتاء. لا كعوب عالية؛ أحذية مسطحة أو أحذية صحراوية مطلوبة. الدفع الكامل عند الحجز. إلغاء مجاني قبل 5 أيام؛ استرداد 50% خلال 72 ساعة؛ لا استرداد خلال 48 ساعة. يعتمد على الطقس: يُعرض التأجيل في حالات العواصف الرملية.`,
  },
  {
    id: 4,
    descriptionEn: `Arabic bread is the oldest continuously made food in the world — and this workshop peels back its millennia of history while teaching you to make it with your bare hands. Led by Ustadha Noura Al-Shammari, a Levantine cuisine educator whose family has been baking khubz for five generations, this session runs in the intimate setting of her home kitchen in Riyadh's Sulaymaniyah district.

The three-hour class opens with a sensory tour of the Levantine pantry: za'atar, sumac, nigella seeds, pomegranate molasses, and the family's house-blended baharat — each one narrated through history and story. You then learn to prepare five traditional breads: thin Damascene khubz, the crispy saj flatbread baked over an open dome fire, ka'ak rings dusted with sesame, fatayer pastries stuffed with spinach and feta, and the festive manaqeesh topped with fresh za'atar and olive oil.

Alongside the bread, Ustadha Noura guides you through building a full mezze spread — hummus pulled from the pot, mutabal still warm from the grill, tabbouleh hand-chopped to the precise Lebanese ratio, and kibbeh nayyeh shaped table-side. The session concludes with a shared lunch of everything made, plus a take-home package of house-blended spices.`,
    descriptionAr: `خبز العرب هو أقدم طعام يُصنع بشكل متواصل في العالم — وهذه الورشة تكشف طبقاته من آلاف السنين بينما تعلّمك صناعته بيديك. تقودها الأستاذة نورا الشمري، معلمة المطبخ الشامي التي طهت عائلتها الخبز لخمسة أجيال متعاقبة، في أجواء المطبخ المنزلي الدافئة في حي السليمانية بالرياض.

تبدأ الدورة الثلاثية الساعات بجولة حسية في مخزن الشام: الزعتر والسماق وحبة البركة ودبس الرمان وخلطة البهارات العائلية السرية — كل واحدة تُحكى عبر التاريخ والقصة. ثم تتعلم تحضير خمسة أنواع من الخبز التقليدي: خبز دمشقي رفيع، وخبز الصاج المقرمش المخبوز على نار الحجر المفتوحة، وكعك السمسم، وفطاير السبانخ والجبنة، ومناقيش الزعتر الطازج وزيت الزيتون الاحتفالية.

إلى جانب الخبز، ترشدك الأستاذة نورا في إعداد مائدة مزة كاملة — حمص يُسحب من الإناء، ومتبل دافئ من الشواية، وتبولة مفرومة يدوياً بنسبة لبنانية دقيقة، وكبة نيئة مُشكَّلة على الطاولة. تختتم الجلسة بغداء مشترك من كل ما صُنع، مع حزمة بهارات منزلية لأخذها.`,
    menuDetailsEn: `Part 1 — The Pantry Tour: Za'atar blend, sumac, nigella seeds, baharat, pomegranate molasses tasting\nPart 2 — Breads (you make all 5):\n• Damascene khubz — thin, pliable flatbread\n• Saj bread — baked on open-flame dome\n• Ka'ak — sesame ring biscuits\n• Fatayer — spinach & feta pastry triangles\n• Manaqeesh — za'atar and olive oil flatbread\nPart 3 — Mezze spread:\n• Hummus bil tahini (from scratch)\n• Mutabal / baba ghannouj\n• Tabbouleh (Lebanese ratio)\n• Kibbeh nayyeh\nShared Lunch: All items made, with labne, olives, pickles, and Arabic tea\nTake-home: House-blended baharat and za'atar spice packs`,
    menuDetailsAr: `الجزء 1 — جولة المخزن: خلطة الزعتر والسماق وحبة البركة والبهارات وتذوق دبس الرمان\nالجزء 2 — الخبز (تصنع الجميع بنفسك):\n• خبز دمشقي — رقيق ومرن\n• خبز الصاج — مخبوز على لهب مكشوف\n• كعك — حلقات سمسم\n• فطاير — مثلثات سبانخ وجبنة\n• مناقيش — خبز الزعتر وزيت الزيتون\nالجزء 3 — مزة كاملة:\n• حمص بالطحينة (من الصفر)\n• متبل / بابا غنوج\n• تبولة (نسبة لبنانية)\n• كبة نيئة\nغداء مشترك: كل ما صُنع مع لبنة وزيتون ومخللات وشاي عربي\nما تأخذه: أكياس بهارات وزعتر من خلطتنا المنزلية`,
    rulesEn: `Open to all skill levels — no cooking experience needed. Minimum age: 8 years (children welcome with supervising adult). Vegetarian-friendly throughout. Gluten allergy cannot be accommodated (bread workshop). Comfortable clothing; aprons provided. Full payment at booking. Free cancellation 48 hours before; 50% refund within 24 hours; no refund same day. Maximum 10 guests per class.`,
    rulesAr: `مفتوح لجميع المستويات — لا خبرة طهي مطلوبة. الحد الأدنى للعمر: 8 سنوات (الأطفال مرحب بهم مع بالغ مشرف). مناسب للنباتيين. لا يمكن استيعاب حساسية الغلوتين (ورشة الخبز). ملابس مريحة؛ مريلة مُقدَّمة. الدفع الكامل عند الحجز. إلغاء مجاني قبل 48 ساعة؛ استرداد 50% خلال 24 ساعة؛ لا استرداد في نفس اليوم. الحد الأقصى 10 ضيوف لكل فصل.`,
  },
  {
    id: 5,
    descriptionEn: `The Eastern Province's greatest culinary treasure is the Gulf — and nowhere does this feel more vivid than at dusk on the Dammam Corniche, where the salt air mingles with the smoke of charcoal grills and the sound of waves punctuates the sizzle of fresh catch. This two-and-a-half-hour beachside grilling experience is part seafood education, part sunset ritual, and entirely unforgettable.

Your host, Pitmaster Saad Al-Dubaisi, has spent twenty years sourcing and grilling the finest Gulf catch along this exact stretch of coastline. He begins each session with a live demonstration of Gulf seafood identification — how to distinguish hammour from farida, which shrimp varieties carry the sweetest flesh, and the signs of the day's best lobster. Then the grill fires light, and guests take turns learning direct-heat and indirect-heat techniques on whole fish, prawns threaded on rosemary skewers, and split lobster basted with saffron butter.

Everything is served at communal tables draped in checked tablecloths: saffron rice, tangy tamarind dipping sauces, fresh-baked khubz, and a salad of local tomatoes, cucumber, and fresh herbs. As the sun drops below the Gulf horizon, the meal transitions into a traditional gahwa round — cardamom coffee and Qatif dates — and the stories begin.`,
    descriptionAr: `أعظم كنز طهوي في المنطقة الشرقية هو الخليج — ولا مكان يبدو فيه هذا أشد وضوحاً من عند الغسق على كورنيش الدمام، حيث يمتزج هواء الملح بدخان مشاوي الفحم وتقاطع أصوات الأمواج فرقعة الأسماك الطازجة. تجربة الشواء الشاطئية هذه التي تمتد لساعتين ونصف هي في جزء منها تعليم مأكولات بحرية، وفي جزء آخر طقس الغروب، وفي مجملها لا تُنسى.

مضيفك، أستاذ الشواء سعد الدبيسي، قضى عشرين عاماً في اقتناء وشواء أجود صيد الخليج على هذا الشاطئ بالذات. يبدأ كل جلسة بعرض حي لتحديد المأكولات البحرية في الخليج — كيف تميّز الهامور عن الفريدة، وأيّ أصناف الروبيان تحمل أطيب لحوم، وعلامات أفضل كركند في اليوم. ثم تشتعل المشاوي ويتناوب الضيوف على تعلم تقنيتَي الحرارة المباشرة وغير المباشرة على السمك الكامل والروبيان المثقوب على أسياخ إكليل الجبل والكركند المشقوق المدهون بزبدة الزعفران.

كل شيء يُقدَّم على طاولات جماعية مفروشة بمفارش مربعات: أرز زعفراني وصلصة تمر هندي لاذعة وخبز طازج وسلطة طماطم محلية وخيار وأعشاب طازجة. مع انحدار الشمس تحت أفق الخليج، تتحوّل الوجبة إلى جولة قهوة تقليدية — قهوة هيل وتمر القطيف — وتبدأ الحكايات.`,
    menuDetailsEn: `Arrival: Gulf shrimp cocktail, tamarind dipping sauce\nDemonstration: Gulf seafood identification and selection guide\nGrilling Session (guests participate):\n• Whole hammour (Gulf grouper) — direct flame\n• Tiger prawns on rosemary skewers — charcoal indirect heat\n• Split spiny lobster — basted with saffron butter\n• Calamari rings — griddle with garlic and lemon\nSides: Saffron rice with dried lime, fresh khubz, fattoush salad, 3 dipping sauces\nFinale: Arabic gahwa (cardamom coffee), Qatif dates, baklava`,
    menuDetailsAr: `الوصول: كوكتيل روبيان خليجي، صلصة تمر هندي\nعرض توضيحي: دليل تحديد واختيار المأكولات البحرية الخليجية\nجلسة الشواء (بمشاركة الضيوف):\n• هامور كامل (سمك المرجان الخليجي) — لهب مباشر\n• روبيان نمر على أسياخ إكليل الجبل — حرارة غير مباشرة من الفحم\n• كركند شائك مشقوق — مدهون بزبدة الزعفران\n• حلقات حبار — شواية بالثوم والليمون\nمرافقات: أرز زعفراني بليمون مجفف، خبز طازج، سلطة فتوش، 3 صلصات\nختام: قهوة عربية (هيل)، تمر القطيف، بقلاوة`,
    rulesEn: `Minimum age: 6 years (children welcome). Seafood and shellfish allergy cannot be accommodated — all dishes contain seafood. Suitable footwear recommended (beach terrain). Warm layer advised November–March. Full payment at booking. Free cancellation 48 hours before; no refund within 24 hours. Weather cancellations receive full refund or reschedule. Maximum 18 guests per session.`,
    rulesAr: `الحد الأدنى للعمر: 6 سنوات (الأطفال مرحب بهم). لا يمكن استيعاب حساسية المأكولات البحرية والقشريات — جميع الأطباق تحتوي على مأكولات بحرية. أحذية مناسبة موصى بها (تضاريس شاطئية). طبقة دافئة مقترحة من نوفمبر إلى مارس. الدفع الكامل عند الحجز. إلغاء مجاني قبل 48 ساعة؛ لا استرداد خلال 24 ساعة. تلغى بسبب الطقس مع استرداد كامل أو إعادة جدولة. الحد الأقصى 18 ضيوفاً لكل جلسة.`,
  },
  {
    id: 6,
    descriptionEn: `In the centuries when the Hejaz was the crossroads of the civilised world, Arabian coffee and dates were the currency of hospitality, diplomacy, and trade. This immersive two-hour journey through Makkah's historic Al Zaher district honours that tradition with scholarly depth and sensory richness rarely found outside specialist research institutions.

Your guide, Dr. Fahad Al-Otaibi — a food historian and former curator at the National Museum of Saudi Arabia — leads guests through twelve date varieties cultivated across the Kingdom, from the buttery Medjool of Al-Ahsa to the dry, almost caramel-crusted Sukkari of Al-Qassim, the fragrant Ajwa of Madinah, and the deep amber Khlass of Hofuf. Each variety is tasted alongside a matched coffee preparation: light-roast khaleeji qahwa steeped with cardamom, the floral Yemeni-style dum, and the bitter ceremonial coffee served at weddings and funerals across the Arabian Peninsula.

The session concludes with a hands-on qahwa brewing lesson using the traditional dallah coffee pot, and each guest departs with a curated gift box containing three date varieties, a blend of roasted qahwa beans, and the booklet "Dates, Coffee and the Hejaz" — a forty-page illustrated cultural guide written by Dr. Al-Otaibi himself.`,
    descriptionAr: `في القرون التي كان فيها الحجاز مفترق طرق العالم المتحضر، كانت القهوة العربية والتمور عملة الضيافة والدبلوماسية والتجارة. تُحيي هذه الرحلة المعمّقة التي تمتد لساعتين في حي الزاهر التاريخي بمكة المكرمة هذا التراث بعمق أكاديمي وثراء حسي نادراً ما نجد مثيله خارج مؤسسات البحث المتخصصة.

مرشدك، الدكتور فهد العتيبي — مؤرخ طعام وأمين متحف سابق في المتحف الوطني للمملكة العربية السعودية — يقود الضيوف عبر اثني عشر صنفاً من التمور المزروعة في أرجاء المملكة: من المجدول الزبداني في الأحساء إلى السكري الجاف شبه المكرمل في القصيم، والعجوة العطرة من المدينة المنورة، والخلاص العنبري العميق من هفوف. يُتذوَّق كل صنف إلى جانب تحضير قهوة مناسب: القهوة الخليجية الفاتحة المعتقة بالهيل، والدم اليمني الزهري، والقهوة الحفلية المرّة المقدَّمة في الأعراس والعزاء عبر شبه الجزيرة العربية.

تختتم الجلسة بدرس عملي في تحضير القهوة بالدلّة التقليدية، ويغادر كل ضيف حاملاً صندوق هدايا منتقى يحتوي على ثلاثة أصناف من التمور وخلطة حبوب القهوة المحمّصة وكتيّب "التمر والقهوة والحجاز" — دليل ثقافي مصوَّر يقع في أربعين صفحة كتبه الدكتور العتيبي بنفسه.`,
    menuDetailsEn: `Date Tasting Flight (12 varieties with provenance cards):\nMedjool (Al-Ahsa), Sukkari (Al-Qassim), Ajwa (Madinah), Khlass (Hofuf), Safawi, Mabroom, Barhi, Ruthana, Sagai, Hilali, Khalas, Nabbut Ali\nCoffee Pairing Progression:\n• Khaleeji qahwa — cardamom, saffron, rose water\n• Yemeni-style dum — floral, lightly spiced\n• Ceremonial bitter coffee — roasted with clove and ginger\nHands-on: Traditional dallah brewing lesson\nTake-home gift box: 3 date varieties (200g each), qahwa bean blend (100g), cultural booklet`,
    menuDetailsAr: `تذوق التمور (12 صنفاً مع بطاقات المصدر):\nمجدول (الأحساء)، سكري (القصيم)، عجوة (المدينة)، خلاص (هفوف)، صفاوي، مبروم، برحي، روثانة، صقاي، هلالي، خلاص، نبوت علي\nتسلسل إقران القهوة:\n• قهوة خليجية — هيل وزعفران وماء ورد\n• دم يمني — زهري خفيف التوابل\n• قهوة حفلية مرّة — محمصة بالقرنفل والزنجبيل\nتطبيق عملي: درس تحضير الدلّة التقليدية\nصندوق الهدايا: 3 أصناف تمر (200 غ كل)، خلطة حبوب قهوة (100 غ)، كتيّب ثقافي`,
    rulesEn: `Open to all ages. Caffeine-free date tasting available for those avoiding coffee. No food allergies concern — dates and coffee only. Modest dress required (Makkah heritage district). Non-Muslims welcome in the heritage district area. Full payment at booking. Free cancellation 48 hours before; 50% refund within 24 hours; no refund same day. Maximum 20 guests per session.`,
    rulesAr: `مفتوح لجميع الأعمار. تذوق تمر بدون كافيين متاح لمن يتجنب القهوة. لا قلق من حساسية الطعام — تمور وقهوة فقط. لباس محتشم مطلوب (حي التراث بمكة). غير المسلمين مرحب بهم في منطقة حي التراث. الدفع الكامل عند الحجز. إلغاء مجاني قبل 48 ساعة؛ استرداد 50% خلال 24 ساعة؛ لا استرداد في نفس اليوم. الحد الأقصى 20 ضيوفاً لكل جلسة.`,
  },
  {
    id: 7,
    descriptionEn: `In a beautifully restored Al Anbariyah heritage house — its carved wooden mashrabiya screens filtering the late afternoon light into shifting gold patterns — the culinary soul of Madinah comes alive across a five-course feast that draws from the ancient Hijazi table, the spice caravan routes, and the collective memory of the city's most respected home cooks.

Your host and storyteller, Umm Khalid, is a fourth-generation Madanite whose family has lived in Al Anbariyah for over a hundred years. Dinner begins with the house's signature jareesh — cracked wheat slow-cooked with camel milk, fried onions, and a tangle of dried herbs that Umm Khalid refuses to name entirely, citing "my grandmother's right to some secrets." The saleeg follows: short-grain rice simmered in camel milk and chicken broth until it becomes silken, spooned beside roasted chicken rubbed with Madinah's distinctive spice blend of turmeric, black pepper, cumin, and dried rose.

The centrepiece is a whole leg of lamb — the madfoon — presented still smoking in its clay pot after four hours underground in the courtyard's traditional pit oven. Each course is narrated through the history of Madinah: the spice trade, the food customs of Hajj season, and the beloved tradition of jama'i (communal) eating that defines the city's identity. The evening ends with fresh Madinah dates, Arabic coffee, and an open invitation to return.`,
    descriptionAr: `في منزل تراثي مُرمَّم في العنبرية — مشبكياته الخشبية المنحوتة تُرشح ضوء العصر الذهبي المتحوّل إلى أنماط ذهبية متغيرة — تنبض روح مدينة المدينة المنورة الطهوية عبر وليمة من خمسة أطباق تستقي من المائدة الحجازية القديمة وطرق قوافل البهارات والذاكرة الجماعية لأعرق طهواتها المنزليات.

مضيفتك وراويتك، أم خالد، مدنية من الجيل الرابع استوطنت عائلتها العنبرية منذ أكثر من مائة عام. يبدأ العشاء بجريش بيتها المميّز — قمح مجروش مطهو ببطء بحليب الإبل والبصل المقلي وحزمة من الأعشاب المجففة التي ترفض أم خالد كشفها بالكامل، مستندةً إلى "حق جدتي في بعض الأسرار." يليه السليق: أرز قصير الحبة مطهو بحليب الإبل ومرق الدجاج حتى يصبح حريرياً، يُقدَّم بجانب دجاج محمص متبّل بخلطة بهارات المدينة المميزة من الكركم والفلفل الأسود والكمون والورد المجفف.

تتجلّى ذروة الوليمة في كامل ساق الضأن — المدفون — يُقدَّم لا يزال يتصاعد منه البخار في قدره الطيني بعد أربع ساعات تحت الأرض في الفرن التقليدي المحفور في الفناء. كل طبق تُشرح روايته عبر تاريخ المدينة: تجارة البهارات وعادات طعام موسم الحج وتقليد الأكل الجماعي الحبيب الذي يُعرّف هوية المدينة. تنتهي الأمسية بتمر مدني طازج وقهوة عربية ودعوة مفتوحة للعودة.`,
    menuDetailsEn: `Arrival: Madinah dates (3 varieties), thin-bread with olive oil and dukkah\nCourse 1: Slow-cooked jareesh (cracked wheat), camel milk, fried onion, dried herb blend (family recipe)\nCourse 2: Saleeg rice — camel milk short-grain, chicken broth, roasted chicken with turmeric-rose spice blend\nCourse 3: Madfoon — whole leg of lamb, pit-roasted 4 hours underground, served in clay pot with spiced rice\nCourse 4: Hashi — camel stew with root vegetables, dried lime, Hejazi herb paste\nCheese & Preserve Board: Camel labneh, dried figs, preserved lemons, mountain honey\nDessert: Madinah khubz with date molasses and samneh (clarified butter), cardamom tea cake\nFinale: Fresh Madinah dates, Arabic coffee (3 rounds), oud incense`,
    menuDetailsAr: `الوصول: تمر مديني (3 أصناف)، خبز رقيق بزيت الزيتون والدقة\nطبق 1: جريش مطهو ببطء (قمح مجروش)، حليب إبل، بصل مقلي، خلطة أعشاب مجففة (وصفة عائلية)\nطبق 2: سليق — أرز قصير الحبة بحليب الإبل ومرق الدجاج، دجاج محمص بخلطة كركم وورد\nطبق 3: المدفون — ساق ضأن كاملة، محمصة في الحفرة 4 ساعات، تُقدَّم في قدر طيني مع أرز متبل\nطبق 4: الهشي — يخنة إبل بالخضروات الجذرية والليمون المجفف وعجينة الأعشاب الحجازية\nلوح جبن ومخللات: لبنة حليب الإبل، تين مجفف، ليمون محفوظ، عسل جبلي\nحلوى: خبز مديني بدبس التمر والسمنة، كعكة الشاي بالهيل\nختام: تمر مديني طازج، قهوة عربية (3 جولات)، بخور عود`,
    rulesEn: `Open to all ages and backgrounds. Non-Muslim guests warmly welcome. Vegetarian alternative available for the lamb course (mushroom madfoon) — notify at booking. No alcohol served. Modest dress respected in the heritage district. Photography welcome throughout. Full payment at booking. Free cancellation 72 hours before; 50% refund within 48 hours; no refund within 24 hours. Maximum 12 guests per dinner.`,
    rulesAr: `مفتوح لجميع الأعمار والخلفيات. الضيوف غير المسلمين مرحب بهم بحرارة. بديل نباتي متاح لطبق الضأن (مدفون الفطر) — يُرجى الإخطار عند الحجز. لا كحول يُقدَّم. اللباس المحتشم يُحترم في حي التراث. التصوير مرحب به طوال الجلسة. الدفع الكامل عند الحجز. إلغاء مجاني قبل 72 ساعة؛ استرداد 50% خلال 48 ساعة؛ لا استرداد خلال 24 ساعة. الحد الأقصى 12 ضيوفاً لكل عشاء.`,
  },
  {
    id: 8,
    descriptionEn: `Jeddah has always looked outward — across the Red Sea to Africa, India, and the ancient spice ports of Zanzibar and Malabar. This exclusive rooftop dinner captures that centuries-old cosmopolitan spirit, setting guests above the Jeddah skyline as the Red Sea turns copper, rose, and finally indigo at dusk.

Chef Sara Al-Ghamdi designs each seasonal menu as a love letter to the Hejazi coast: a culinary landscape shaped by Arabian, African, Persian, and South Asian influences accumulated over fifteen centuries of maritime trade. The seven-course progression begins with Jeddah-style saloona — a saffron-rich fish broth that fishermen have drunk for breakfast since the days of the Ottoman province — and builds toward a spectacular centrepiece of whole-baked Red Sea samak mandi, buried in fragrant wood-smoked rice with caramelized onions, dried limes, and the chef's signature Hejazi spice blend.

The rooftop is open to the stars with the lights of the old Al-Balad quarter visible in the distance. A live oud and violin duo plays throughout the evening, and the night ends with a traditional bakhoor incense ritual — a Jeddah hosting custom that signals the perfect end of a perfect meal.`,
    descriptionAr: `جدة دائماً تتطلع إلى الخارج — عبر البحر الأحمر نحو أفريقيا والهند وموانئ البهارات القديمة في زنجبار وملبار. يلتقط هذا العشاء الحصري على السطح ذلك الروح الكوزموبوليتي العريق، يُقيم الضيوف فوق أفق جدة فيما يتحوّل البحر الأحمر إلى النحاسي فالوردي ثم النيلي عند الغسق.

تُصمم الشيفة سارة الغامدي كل قائمة موسمية كرسالة حب إلى الساحل الحجازي: مشهد طهوي شكّلته تأثيرات عربية وأفريقية وفارسية وجنوب آسيوية تراكمت على مدى خمسة عشر قرناً من التجارة البحرية. يبدأ المسار المتكون من سبعة أطباق بسالونة جدة — مرق سمك غني بالزعفران شربه الصيادون للإفطار منذ أيام الولاية العثمانية — ويتصاعد نحو تحفة رئيسية مبهرة: سمك مندي أحمر بحري مخبوز كاملاً، مدفون في أرز مدخن عطري بالبصل المكرمل والليمون المجفف وخلطة بهارات الشيفة الحجازية الخاصة.

السطح مفتوح على النجوم مع أضواء حي البلد القديم المرئية في الأفق. يعزف ثنائي عود وكمان حي طوال الأمسية، وتختتم الليلة بطقس بخور البخور التقليدي — عادة استضافة جدة التي تُعلن نهاية المثالية لوجبة مثالية.`,
    menuDetailsEn: `Welcome: Jeddah-style saloona (saffron fish broth), roasted pine nuts\nCourse 1: Red Sea ceviche — samak sayyadiyah style, lime, pomegranate, micro herbs\nCourse 2: Grilled hammour, Hejazi spice crust, beurre blanc with preserved lemon\nCourse 3: Camel milk risotto, saffron, dried lime zest, grilled shrimp\nCourse 4: Whole-baked Red Sea samak mandi — wood-smoked basmati rice, caramelized onion, dried lime\nCourse 5: Lamb kabsa, spiced butter rice, caramelized almonds and raisins\nCheese: Camel labneh, local honey, za'atar\nDessert: Om Ali — warm bread pudding with cream, pistachios, rose water\nFinale: Bakhoor incense ritual, Arabic coffee, Ramadan-style tamr and ma'amoul`,
    menuDetailsAr: `ترحيب: سالونة جدة (مرق سمك زعفراني)، صنوبر محمص\nطبق 1: سيفيتشي بحر أحمر — أسلوب سمك الصياديه، ليمون ورمان وأعشاب صغيرة\nطبق 2: هامور مشوي، قشرة بهارات حجازية، صلصة بير بلان بليمون محفوظ\nطبق 3: ريزوتو حليب الإبل، زعفران، قشر ليمون مجفف، روبيان مشوي\nطبق 4: سمك مندي أحمر بحري مخبوز كاملاً — أرز بسمتي مدخن، بصل مكرمل، ليمون مجفف\nطبق 5: كبسة ضأن، أرز متبل بالسمن، لوز مكرمل وزبيب\nجبن: لبنة حليب الإبل، عسل محلي، زعتر\nحلوى: أم علي — بودينغ خبز دافئ بالكريمة والفستق وماء الورد\nختام: طقس بخور، قهوة عربية، تمر ومعمول رمضاني`,
    rulesEn: `Minimum age: 10 years. Seasonal menu changes monthly — ingredients subject to market availability. Seafood allergy cannot be accommodated (most courses contain Red Sea fish). Vegetarian alternative available for fish courses — notify at booking. Smart casual dress; no sportswear. Full payment at booking. Free cancellation 72 hours before; 50% refund within 48 hours; no refund within 24 hours. Maximum 16 guests per dinner.`,
    rulesAr: `الحد الأدنى للعمر: 10 سنوات. القائمة الموسمية تتغير شهرياً — المكونات خاضعة لتوافر السوق. لا يمكن استيعاب حساسية المأكولات البحرية (معظم الأطباق تحتوي على سمك البحر الأحمر). بديل نباتي متاح لأطباق السمك — يُرجى الإخطار عند الحجز. لباس شبه رسمي؛ لا ملابس رياضية. الدفع الكامل عند الحجز. إلغاء مجاني قبل 72 ساعة؛ استرداد 50% خلال 48 ساعة؛ لا استرداد خلال 24 ساعة. الحد الأقصى 16 ضيوفاً لكل عشاء.`,
  },
  {
    id: 9,
    descriptionEn: `Kabsa is the national dish of Saudi Arabia — but what most people eat is a shortcut version, a simplification of a culinary tradition that in its authentic form requires patience, technique, and a deep understanding of spice layering accumulated over generations. This four-hour cooking masterclass dismantles and rebuilds that tradition from its foundations, taught by Chef Khalid Al-Maliki, a Najdi culinary heritage researcher who has spent fifteen years documenting traditional Saudi cooking methods.

The session begins with the most important lesson: the spice blend. Participants grind their own baharat — seven spices including whole cloves, green cardamom, cinnamon sticks, dried rose, and mountain black pepper — using a traditional stone mortar, understanding why proportion and freshness are the variables that separate an ordinary kabsa from a transcendent one. You then break down a whole chicken with traditional knife techniques, learning the fat-rendering process that forms the foundational flavour base of every great kabsa.

The mandi portion of the class introduces the underground cooking tradition: a miniature pit is demonstrated over live coals, and participants understand the smoke, time, and temperature principles that make mandi lamb fall from the bone after hours underground. The masterclass culminates in a communal lunch served on a traditional sufrah mat — everyone eating together from shared platters in the old Najdi style.`,
    descriptionAr: `الكبسة هي الطبق الوطني للمملكة العربية السعودية — لكن ما يأكله معظم الناس نسخة مختصرة، تبسيط لتقليد طهوي يستلزم في شكله الأصيل الصبر والتقنية وفهماً عميقاً لتطبيق البهارات المتراكم عبر أجيال. تفكّك هذه الدورة الاحترافية بمدتها الأربع ساعات ذلك التقليد وتُعيد بناءه من أسسه، يعلّمها الشيف خالد المالكي، باحث في التراث الطهوي النجدي قضى خمسة عشر عاماً في توثيق طرق الطبخ السعودية التقليدية.

تبدأ الجلسة بأهم درس: خلطة البهارات. يطحن المشاركون بهاراتهم الخاصة — سبع توابل تشمل القرنفل الكامل والهيل الأخضر وعيدان القرفة والورد المجفف والفلفل الأسود الجبلي — باستخدام هاون حجري تقليدي، ليفهموا لماذا النسبة والطزاجة هما المتغيران اللذان يفصلان كبسة عادية عن كبسة تسمو إلى مستوى آخر. ثم تُفكّك دجاجة كاملة بتقنيات سكاكين تقليدية، متعلماً عملية استخراج الدهن التي تُشكّل القاعدة النكهية لكل كبسة عظيمة.

قسم المندي من الدورة يُعرّف بتقليد الطهي تحت الأرض: تُعرض حفرة مصغرة على جمر حي، ويفهم المشاركون مبادئ الدخان والزمن ودرجة الحرارة التي تجعل ضأن المندي يتساقط عن العظم بعد ساعات تحت الأرض. تتوّج الدورة بغداء جماعي يُقدَّم على سفرة تقليدية — الجميع يأكل معاً من أطباق مشتركة على الطريقة النجدية القديمة.`,
    menuDetailsEn: `Hands-on Lesson 1: Baharat spice blend — grinding 7 spices on stone mortar, calibrating proportions\nHands-on Lesson 2: Chicken breakdown — Saudi knife techniques, fat rendering, golden broth base\nHands-on Lesson 3: Kabsa rice — loomi (dried lime), saffron blooming, layering method, the critical rest period\nHands-on Lesson 4: Mandi pit demonstration — smoke calibration, clay sealing technique, timing science\nDemonstration: Hashi (camel stew), jareesh (cracked wheat), harees (wheat porridge)\nCommunal Sufrah Lunch:\n• Kabsa (chicken and rice you made)\n• Mandi lamb (pit-cooked from morning)\n• Mutabbaq (stuffed pastry)\n• Salata Arabiya, house pickles, salted labneh\nTake-home: Stone-ground baharat blend (100g), recipe booklet (in Arabic and English)`,
    menuDetailsAr: `درس تطبيقي 1: خلطة البهارات — طحن 7 توابل على هاون حجري، معايرة النسب\nدرس تطبيقي 2: تفكيك الدجاجة — تقنيات السكاكين السعودية، استخراج الدهن، قاعدة المرق الذهبي\nدرس تطبيقي 3: أرز الكبسة — لومي (ليمون مجفف)، إضافة الزعفران، طريقة التطبيق، فترة الراحة الحرجة\nدرس تطبيقي 4: عرض حفرة المندي — معايرة الدخان، تقنية إغلاق الطين، علم التوقيت\nعروض توضيحية: هشي (يخنة إبل)، جريش (قمح مجروش)، هريس (عصيدة قمح)\nغداء سفرة جماعي:\n• كبسة (الدجاج والأرز الذي صنعته)\n• مندي ضأن (مطهو في الحفرة منذ الصباح)\n• مطبق (معجنات محشوة)\n• سلطة عربية، مخللات بيتية، لبنة مملحة\nما تأخذه: خلطة بهارات مطحونة على الحجر (100 غ)، كتيّب وصفات (بالعربية والإنجليزية)`,
    rulesEn: `Open to all skill levels. Minimum age: 10 years. Children under 16 must be accompanied by an adult. Vegetarian fully accommodated (chicken can be replaced with mushroom kabsa and vegetable mandi). Gluten-free alternative rice dishes available. Full payment at booking. Free cancellation 48 hours before; 50% refund within 24 hours; no refund same day. Maximum 12 guests per class.`,
    rulesAr: `مفتوح لجميع المستويات. الحد الأدنى للعمر: 10 سنوات. الأطفال دون 16 سنة يجب أن يكونوا مع بالغ. نباتي مُستوعب بالكامل (يمكن استبدال الدجاج بكبسة الفطر ومندي الخضروات). أطباق أرز بديلة خالية من الغلوتين متاحة. الدفع الكامل عند الحجز. إلغاء مجاني قبل 48 ساعة؛ استرداد 50% خلال 24 ساعة؛ لا استرداد في نفس اليوم. الحد الأقصى 12 ضيوفاً لكل فصل.`,
  },
  {
    id: 10,
    descriptionEn: `After the sun drops behind the ancient walls of Diriyah — the birthplace of the Saudi state, a UNESCO World Heritage Site, and arguably the most atmospheric place in the Arabian Peninsula after dark — the old mud-brick lanes of the At-Turaif district transform into a living street food festival unlike anything else in the Kingdom.

This guided two-hour walking tour is led by Moudhi Al-Rashid, a food journalist and Diriyah heritage specialist who has mapped every kitchen, cart, and pop-up vendor in the district. The tour begins at the Wadi Hanifa viewpoint, where the old city spills down the hillside and the valley lights flicker below, before moving through seven curated stops: the mutabbaq vendor who folds his egg-and-meat pastry over a flat iron; the harees stirrer who has kept the same wood-fire going since before his father died; the raqaq bread maker who stretches dough to almost transparent thinness; and the legendary Diriyah halwa seller whose sesame-and-saffron confection has been made by the same family for four generations.

Each stop includes a full tasting portion and the story behind the dish — its history, its regional variations, and its place in Diriyah's food culture. The walk ends with a shared plate of mixed mutton and chicken alongside fresh-baked khubz at a traditional communal table, with the At-Turaif palace walls lit dramatically against the night sky.`,
    descriptionAr: `بعد أن تغيب الشمس وراء أسوار الدرعية القديمة — مهد الدولة السعودية وموقع التراث العالمي لليونسكو والمكان الأكثر أثراً في شبه الجزيرة العربية بعد الغسق — تتحوّل أزقة حي الطريف الطينية القديمة إلى مهرجان طعام شعبي حي لا مثيل له في المملكة.

تقود هذه الجولة المرشدة سيراً لمدة ساعتين الصحفية الطهوية مضاوي الراشد، المتخصصة في تراث الدرعية التي رسمت خريطة كل مطبخ وعربة وبائع متجول في الحي. تبدأ الجولة من منظر وادي حنيفة حيث تنحدر المدينة القديمة على جانب التل وتتلألأ أضواء الوادي في الأسفل، قبل أن تنتقل عبر سبع محطات منتقاة: بائع المطبق الذي يطوي معجنة البيض واللحم على حديدة مسطحة؛ ومحرّك الهريس الذي يُبقي النار نفسها مشتعلة منذ ما قبل وفاة والده؛ وصانعة خبز الرقاق التي تمدّ العجين إلى رقة شبه شفافة؛ وبائع حلوى الدرعية الأسطوري الذي تصنع عائلته الحلوى من السمسم والزعفران منذ أربعة أجيال.

كل محطة تشمل حصة تذوق كاملة وقصة الطبق — تاريخه وتنويعاته الإقليمية ومكانته في الثقافة الطهوية للدرعية. تنتهي الجولة بطبق مشترك من الضأن والدجاج المشكل مع خبز طازج على طاولة جماعية تقليدية، مع أسوار قصر الطريف المضاءة بشكل درامي في مواجهة السماء الليلية.`,
    menuDetailsEn: `Stop 1 — Wadi Hanifa Viewpoint: Mildly spiced camel milk sharbat (welcome drink)\nStop 2 — Mutabbaq Stall: Mutabbaq (egg, minced mutton, herbs) — full portion\nStop 3 — Harees Cart: Diriyah harees — slow-wheat porridge with samneh drizzle\nStop 4 — Raqaq Baker: Fresh raqaq flatbread with date paste and soft white cheese\nStop 5 — Saleeg Stop: Saleeg rice with roasted chicken, bone broth reduction\nStop 6 — Halwa Workshop: Diriyah sesame-saffron halwa, with fresh-cut tasting portion\nStop 7 — Communal Finish Table: Mixed mutton and chicken tray, fresh khubz, Arabic salad, full spread\nDrinks throughout: Arabic coffee (2 rounds), hibiscus, laban (yoghurt drink)`,
    menuDetailsAr: `محطة 1 — منظر وادي حنيفة: شربات حليب الإبل خفيف التوابل (مشروب ترحيبي)\nمحطة 2 — كشك المطبق: مطبق (بيض ولحم مفروم وأعشاب) — حصة كاملة\nمحطة 3 — عربة الهريس: هريس الدرعية — عصيدة قمح بطيئة بالسمنة\nمحطة 4 — خبّازة الرقاق: خبز رقاق طازج مع معجون التمر والجبن الأبيض الطري\nمحطة 5 — محطة السليق: أرز سليق مع دجاج محمص وتخفيض مرق العظم\nمحطة 6 — ورشة الحلوى: حلوى السمسم والزعفران الدرعية، مع حصة تذوق طازجة\nمحطة 7 — طاولة الختام الجماعية: صينية ضأن ودجاج مشكل، خبز طازج، سلطة عربية، مائدة كاملة\nمشروبات طوال الجولة: قهوة عربية (جولتان)، كركديه، لبن`,
    rulesEn: `Minimum age: 6 years. Comfortable walking shoes required — approximately 2km total distance. Not suitable for wheelchair users (historic cobblestone paths). Vegetarian welcome — vendor alternatives arranged in advance if notified at booking. Nut allergy: sesame widely used; cannot be fully avoided. Depart on time — the vendor circuit is time-sensitive. Full payment at booking. Free cancellation 48 hours before; 50% refund within 24 hours; no refund same day. Maximum 12 guests per tour.`,
    rulesAr: `الحد الأدنى للعمر: 6 سنوات. أحذية مريحة للمشي مطلوبة — المسافة الإجمالية حوالي 2 كم. غير مناسب لمستخدمي الكراسي المتحركة (مسالك حجرية تاريخية). النباتيون مرحب بهم — بدائل البائعين تُرتَّب مسبقاً إذا أُخطر عند الحجز. حساسية المكسرات: السمسم مستخدم على نطاق واسع؛ لا يمكن تجنبه بالكامل. المغادرة في الوقت المحدد — دائرة البائعين حساسة للوقت. الدفع الكامل عند الحجز. إلغاء مجاني قبل 48 ساعة؛ استرداد 50% خلال 24 ساعة؛ لا استرداد في نفس اليوم. الحد الأقصى 12 ضيوفاً لكل جولة.`,
  },
];

async function main() {
  console.log("✍️  Enriching experience descriptions, menu details, and rules...\n");

  for (const exp of ENRICHED) {
    await db
      .update(experiencesTable)
      .set({
        descriptionEn: exp.descriptionEn,
        descriptionAr: exp.descriptionAr,
        menuDetailsEn: exp.menuDetailsEn,
        menuDetailsAr: exp.menuDetailsAr,
        rulesEn: exp.rulesEn,
        rulesAr: exp.rulesAr,
      })
      .where(eq(experiencesTable.id, exp.id));

    const enLen = exp.descriptionEn.length;
    const arLen = exp.descriptionAr.length;
    console.log(`  ✓ Experience ${exp.id}: ${enLen}en / ${arLen}ar chars`);
  }

  console.log("\n✅ All 10 experiences enriched successfully.");
}

main().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
