import { db } from "@workspace/db";
import { dishesTable } from "@workspace/db/schema";
import { eq } from "drizzle-orm";

interface DishSeed {
  restaurantId: number;
  nameEn: string;
  nameAr: string;
  descriptionEn: string;
  descriptionAr: string;
  price: string;
  imageUrl?: string;
  calories?: number;
  prepTimeMinutes?: number;
  spiceLevel?: number;
  isHalal?: boolean;
  isVegetarian?: boolean;
  isVegan?: boolean;
  isGlutenFree?: boolean;
  isDairyFree?: boolean;
  isNutFree?: boolean;
  isHealthy?: boolean;
  isTabaqStar?: boolean;
  isBestseller?: boolean;
  isChefChoice?: boolean;
  isNewItem?: boolean;
  isMostOrdered?: boolean;
  avgRating?: string;
  reviewCount?: number;
  popularityScore?: string;
  allergens?: string[];
}

const DISHES: DishSeed[] = [
  // ─── Najd Village (restaurant_id: 1) ───────────────────────────────────────
  {
    restaurantId: 1,
    nameEn: "Mutabbaq",
    nameAr: "مطبق",
    descriptionEn: "Crispy folded pastry filled with spiced minced lamb, egg, onion and green onion — a Najdi street classic elevated to fine dining.",
    descriptionAr: "فطيرة مطوية مقرمشة محشوة بلحم الضأن المفروم المتبل والبيض والبصل والبصل الأخضر — كلاسيكية الشارع النجدي ترتقي إلى المطاعم الراقية.",
    price: "55.00",
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    calories: 520,
    prepTimeMinutes: 20,
    spiceLevel: 1,
    isHalal: true,
    isBestseller: true,
    avgRating: "4.7",
    reviewCount: 38,
    popularityScore: "88.5",
    allergens: ["gluten", "eggs"],
  },
  {
    restaurantId: 1,
    nameEn: "Saleeg",
    nameAr: "سليق",
    descriptionEn: "Velvety white rice slow-cooked in rich bone broth with cardamom and cloves, topped with roasted chicken and drizzled with ghee.",
    descriptionAr: "أرز أبيض مخملي يُطهى ببطء في مرق عظام غني بالهيل والقرنفل، مُزيَّن بدجاج محمر ورذاذ سمن.",
    price: "75.00",
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop",
    calories: 680,
    prepTimeMinutes: 45,
    spiceLevel: 1,
    isHalal: true,
    isChefChoice: true,
    avgRating: "4.9",
    reviewCount: 52,
    popularityScore: "94.0",
    allergens: [],
  },
  {
    restaurantId: 1,
    nameEn: "Margoog",
    nameAr: "مرقوق",
    descriptionEn: "Hearty slow-cooked stew with tender lamb, root vegetables and thin flatbread, simmered in a aromatic saffron and spice broth.",
    descriptionAr: "يخنة دسمة مطبوخة ببطء بلحم الضأن الطري والخضروات الجذرية والخبز الرقيق، تُطهى في مرق عطر بالزعفران والتوابل.",
    price: "95.00",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop",
    calories: 820,
    prepTimeMinutes: 60,
    spiceLevel: 2,
    isHalal: true,
    isTabaqStar: true,
    avgRating: "4.8",
    reviewCount: 61,
    popularityScore: "96.2",
    allergens: ["gluten"],
  },
  {
    restaurantId: 1,
    nameEn: "Muhallabia",
    nameAr: "مهلبية",
    descriptionEn: "Traditional rose-scented milk pudding, delicately set and garnished with crushed pistachios, dried rose petals and orange blossom.",
    descriptionAr: "حلوى الحليب التقليدية المعطرة بالورد، مُزيَّنة بالفستق المطحون وبتلات الورد المجففة وماء الزهر.",
    price: "35.00",
    imageUrl: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&h=400&fit=crop",
    calories: 280,
    prepTimeMinutes: 10,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isGlutenFree: true,
    isBestseller: true,
    avgRating: "4.6",
    reviewCount: 44,
    popularityScore: "87.0",
    allergens: ["dairy", "nuts"],
  },
  {
    restaurantId: 1,
    nameEn: "Aseedah",
    nameAr: "عصيدة",
    descriptionEn: "Dense sorghum porridge drizzled with date molasses and pure ghee — a timeless Najdi comfort dessert with ancestral roots.",
    descriptionAr: "عصيدة الذرة الكثيفة مع دبس التمر والسمن الخالص — حلوى نجدية تقليدية أصيلة.",
    price: "28.00",
    imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&h=400&fit=crop",
    calories: 390,
    prepTimeMinutes: 15,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: false,
    isNewItem: false,
    avgRating: "4.5",
    reviewCount: 29,
    popularityScore: "80.0",
    allergens: ["dairy"],
  },

  // ─── Reem Al Bawadi (restaurant_id: 2) ─────────────────────────────────────
  {
    restaurantId: 2,
    nameEn: "Hummus with Lamb",
    nameAr: "حمص باللحمة",
    descriptionEn: "Silky chickpea hummus topped with spiced minced lamb, toasted pine nuts and a drizzle of extra-virgin olive oil. Served with fresh flatbread.",
    descriptionAr: "حمص ناعم بالحمص مع لحم مفروم متبل وصنوبر محمص وزيت زيتون بكر ممتاز. يُقدَّم مع خبز طازج.",
    price: "38.00",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=600&h=400&fit=crop",
    calories: 420,
    prepTimeMinutes: 12,
    spiceLevel: 1,
    isHalal: true,
    isBestseller: true,
    avgRating: "4.7",
    reviewCount: 55,
    popularityScore: "91.0",
    allergens: ["gluten", "sesame"],
  },
  {
    restaurantId: 2,
    nameEn: "Mixed Heritage Mezze",
    nameAr: "مزة تراثية مشكلة",
    descriptionEn: "A platter of 8 artisan mezze including mutabbaq, grape leaves, kibbeh, fattoush, tabbouleh, baba ghannouj, labneh and falafel.",
    descriptionAr: "صحن يضم 8 أصناف من المزة المصنوعة يدوياً: مطبق، ورق عنب، كبة، فتوش، تبولة، بابا غنوج، لبنة وفلافل.",
    price: "85.00",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop",
    calories: 780,
    prepTimeMinutes: 20,
    spiceLevel: 1,
    isHalal: true,
    isVegetarian: false,
    isTabaqStar: true,
    isChefChoice: true,
    avgRating: "4.8",
    reviewCount: 72,
    popularityScore: "95.5",
    allergens: ["gluten", "sesame", "dairy"],
  },
  {
    restaurantId: 2,
    nameEn: "Mixed Grill Platter",
    nameAr: "مشاوي مشكلة",
    descriptionEn: "Generous platter of shish tawook, lamb kebabs, kofta, and grilled hammour fillet — all charcoal-grilled and served with garlic sauce and bread.",
    descriptionAr: "صحن سخي من الشيش طاووق وكباب الضأن والكفتة وفيليه الحمور المشوي — جميعها مشوية على الفحم مع صوص الثوم والخبز.",
    price: "155.00",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
    calories: 1100,
    prepTimeMinutes: 30,
    spiceLevel: 2,
    isHalal: true,
    isMostOrdered: true,
    avgRating: "4.9",
    reviewCount: 88,
    popularityScore: "97.0",
    allergens: ["gluten"],
  },
  {
    restaurantId: 2,
    nameEn: "Madfoon Lamb",
    nameAr: "لحم المدفون",
    descriptionEn: "Whole Hejazi-spiced lamb slow-cooked underground for 8 hours on fragrant rice. A communal dish steeped in Saudi tradition.",
    descriptionAr: "خروف كامل بتوابل حجازية مطبوخ تحت الأرض لـ8 ساعات على أرز عطر. طبق جماعي يعكس التراث السعودي الأصيل.",
    price: "280.00",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    calories: 1400,
    prepTimeMinutes: 480,
    spiceLevel: 2,
    isHalal: true,
    isChefChoice: true,
    avgRating: "4.9",
    reviewCount: 41,
    popularityScore: "93.5",
    allergens: [],
  },
  {
    restaurantId: 2,
    nameEn: "Fattoush Salad",
    nameAr: "سلطة فتوش",
    descriptionEn: "Levantine bread salad with crispy pita shards, fresh tomato, cucumber, purslane and a tangy pomegranate-sumac dressing.",
    descriptionAr: "سلطة فتوش شامية مع قطع الخبز المقرمش، الطماطم الطازجة، الخيار، الفرفحينة وصوص الرمان والسماق اللاذع.",
    price: "32.00",
    imageUrl: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600&h=400&fit=crop",
    calories: 240,
    prepTimeMinutes: 10,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isHealthy: true,
    avgRating: "4.5",
    reviewCount: 33,
    popularityScore: "82.0",
    allergens: ["gluten"],
  },
  {
    restaurantId: 2,
    nameEn: "Knafeh",
    nameAr: "كنافة",
    descriptionEn: "Warm shredded phyllo pastry layered with sweet akkawi cheese, drenched in fragrant orange-blossom syrup and topped with crushed pistachios.",
    descriptionAr: "كنافة دافئة من الشعيرية المقرمشة مع جبن العكاوي الحلو، مغمورة بشراب ماء الزهر ومُزيَّنة بالفستق المطحون.",
    price: "42.00",
    imageUrl: "https://images.unsplash.com/photo-1607478900766-efe13248b125?w=600&h=400&fit=crop",
    calories: 520,
    prepTimeMinutes: 15,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isBestseller: true,
    avgRating: "4.8",
    reviewCount: 67,
    popularityScore: "93.0",
    allergens: ["gluten", "dairy", "nuts"],
  },

  // ─── Sushi Sama (restaurant_id: 3) ─────────────────────────────────────────
  {
    restaurantId: 3,
    nameEn: "Salmon Nigiri (3 pcs)",
    nameAr: "نيغيري السلمون (3 قطع)",
    descriptionEn: "Three pristine slices of Tasmanian salmon over perfectly seasoned shari rice, finished with a touch of yuzu zest.",
    descriptionAr: "ثلاث شرائح من سلمون تسمانيا الطازج فوق أرز شاري متبل بدقة، مع لمسة من قشر اليوزو.",
    price: "48.00",
    imageUrl: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&h=400&fit=crop",
    calories: 185,
    prepTimeMinutes: 5,
    spiceLevel: 0,
    isHalal: true,
    isDairyFree: true,
    isGlutenFree: true,
    isTabaqStar: true,
    avgRating: "4.9",
    reviewCount: 78,
    popularityScore: "96.8",
    allergens: ["fish", "sesame"],
  },
  {
    restaurantId: 3,
    nameEn: "Wagyu Beef Maki",
    nameAr: "واغيو بيف ماكي",
    descriptionEn: "Premium Miyazaki A5 Wagyu beef thinly sliced over inside-out rolls with truffle mayo, crispy onion and micro shiso.",
    descriptionAr: "شرائح رفيعة من لحم واغيو ميازاكي A5 الفاخر على رول مقلوب مع مايونيز الكمأة والبصل المقرمش والشيسو الصغير.",
    price: "95.00",
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&h=400&fit=crop",
    calories: 340,
    prepTimeMinutes: 12,
    spiceLevel: 0,
    isHalal: true,
    isChefChoice: true,
    isNewItem: true,
    avgRating: "4.9",
    reviewCount: 42,
    popularityScore: "95.2",
    allergens: ["gluten", "sesame", "eggs"],
  },
  {
    restaurantId: 3,
    nameEn: "Miso Soup",
    nameAr: "شوربة ميسو",
    descriptionEn: "Classic dashi-based white miso soup with silken tofu, wakame seaweed and spring onion — the ideal sushi companion.",
    descriptionAr: "شوربة ميسو أبيض على قاعدة داشي الكلاسيكية مع التوفو الناعم وعشب الواكامي والبصل الأخضر.",
    price: "18.00",
    imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&h=400&fit=crop",
    calories: 65,
    prepTimeMinutes: 5,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isHealthy: true,
    avgRating: "4.4",
    reviewCount: 31,
    popularityScore: "79.0",
    allergens: ["soy"],
  },
  {
    restaurantId: 3,
    nameEn: "Tempura Prawn (6 pcs)",
    nameAr: "تمبورا روبيان (6 قطع)",
    descriptionEn: "Six tiger prawns in a gossamer tempura batter, served with tentsuyu dipping sauce and a heap of finely grated daikon.",
    descriptionAr: "ستة جمبري نمري بعجينة تمبورا خفيفة، تُقدَّم مع صوص تينتسويو وكومة من الفجل المبشور ناعماً.",
    price: "68.00",
    imageUrl: "https://images.unsplash.com/photo-1607631568010-a87245c0daf8?w=600&h=400&fit=crop",
    calories: 310,
    prepTimeMinutes: 15,
    spiceLevel: 0,
    isHalal: true,
    isMostOrdered: true,
    avgRating: "4.7",
    reviewCount: 58,
    popularityScore: "90.5",
    allergens: ["gluten", "shellfish"],
  },
  {
    restaurantId: 3,
    nameEn: "Chirashi Bowl",
    nameAr: "وعاء شيراشي",
    descriptionEn: "A generous bowl of seasoned shari rice topped with 10 kinds of premium sashimi, ikura, uni, tamago and cucumber.",
    descriptionAr: "وعاء سخي من أرز شاري المتبل مع 10 أنواع من الساشيمي الفاخر والإيكورا والأوني والتاماغو والخيار.",
    price: "98.00",
    imageUrl: "https://images.unsplash.com/photo-1617196034843-a45f93b3fc2e?w=600&h=400&fit=crop",
    calories: 520,
    prepTimeMinutes: 15,
    spiceLevel: 0,
    isHalal: true,
    isDairyFree: true,
    isGlutenFree: true,
    isTabaqStar: false,
    isBestseller: true,
    avgRating: "4.8",
    reviewCount: 49,
    popularityScore: "92.8",
    allergens: ["fish", "shellfish", "sesame", "eggs"],
  },
  {
    restaurantId: 3,
    nameEn: "Edamame",
    nameAr: "إيدامامي",
    descriptionEn: "Steamed young soybeans tossed in sea salt — the perfect light starter or sake companion.",
    descriptionAr: "فول الصويا الطازج المطهو على البخار مع ملح البحر — مقبلة خفيفة مثالية أو مرافقة للساكي.",
    price: "22.00",
    imageUrl: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&h=400&fit=crop",
    calories: 110,
    prepTimeMinutes: 5,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    isHealthy: true,
    avgRating: "4.3",
    reviewCount: 24,
    popularityScore: "76.0",
    allergens: ["soy"],
  },

  // ─── Lusin (restaurant_id: 4) ────────────────────────────────────────────────
  {
    restaurantId: 4,
    nameEn: "Khorovats Lamb Skewers",
    nameAr: "أسياخ الخروف خوروفاتس",
    descriptionEn: "Marinated Najdi lamb cubes grilled over vine wood with Caucasian herbs, pomegranate molasses and dried barberry.",
    descriptionAr: "مكعبات لحم ضأن نجدي متبلة ومشوية على خشب الكرمة بأعشاب قوقازية ودبس الرمان والبربريس المجفف.",
    price: "185.00",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
    calories: 720,
    prepTimeMinutes: 35,
    spiceLevel: 1,
    isHalal: true,
    isChefChoice: true,
    isTabaqStar: true,
    avgRating: "4.9",
    reviewCount: 63,
    popularityScore: "96.5",
    allergens: [],
  },
  {
    restaurantId: 4,
    nameEn: "Walnut Manti Dumplings",
    nameAr: "مانتي الجوز",
    descriptionEn: "Hand-folded Armenian dumplings filled with spiced walnut and onion, served in a warm yogurt-garlic sauce with Aleppo pepper butter.",
    descriptionAr: "زلابية أرمنية مطوية يدوياً محشوة بالجوز المتبل والبصل، تُقدَّم في صوص الزبادي والثوم الدافئ مع زبدة فلفل حلب.",
    price: "95.00",
    imageUrl: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=600&h=400&fit=crop",
    calories: 480,
    prepTimeMinutes: 25,
    spiceLevel: 2,
    isHalal: true,
    isVegetarian: true,
    isBestseller: true,
    avgRating: "4.8",
    reviewCount: 57,
    popularityScore: "93.8",
    allergens: ["gluten", "dairy", "nuts"],
  },
  {
    restaurantId: 4,
    nameEn: "Stuffed Grape Leaves",
    nameAr: "ورق عنب محشو",
    descriptionEn: "Vine leaves stuffed with herb-scented rice, pine nuts and currants, served cold with labna and a squeeze of lemon.",
    descriptionAr: "أوراق عنب محشوة بأرز عطر بالأعشاب والصنوبر وزبيب الكشمش، تُقدَّم باردة مع اللبنة وعصير الليمون.",
    price: "55.00",
    imageUrl: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=600&h=400&fit=crop",
    calories: 310,
    prepTimeMinutes: 15,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: false,
    isHealthy: true,
    avgRating: "4.6",
    reviewCount: 38,
    popularityScore: "85.0",
    allergens: ["gluten", "dairy", "nuts"],
  },
  {
    restaurantId: 4,
    nameEn: "Lahmacun",
    nameAr: "لحم عجين",
    descriptionEn: "Thin flatbread spread with a mix of minced lamb, tomato, herbs and Urfa pepper, baked at high heat and rolled with parsley and lemon.",
    descriptionAr: "خبز رقيق ممتد بمزيج من اللحم المفروم والطماطم والأعشاب وفلفل أورفة، يُخبز على نار عالية ويُلف مع البقدونس والليمون.",
    price: "42.00",
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    calories: 380,
    prepTimeMinutes: 15,
    spiceLevel: 2,
    isHalal: true,
    isMostOrdered: true,
    avgRating: "4.7",
    reviewCount: 46,
    popularityScore: "88.5",
    allergens: ["gluten"],
  },
  {
    restaurantId: 4,
    nameEn: "Armenian Baklava",
    nameAr: "بقلاوة أرمنية",
    descriptionEn: "Diamond-cut layers of crisp filo pastry with spiced walnut filling, soaked in a honey and orange blossom syrup.",
    descriptionAr: "طبقات من عجينة الفيلو المقرمشة مقطوعة على شكل الماس مع حشو الجوز المتبل، منقوعة في شراب العسل وماء الزهر.",
    price: "32.00",
    imageUrl: "https://images.unsplash.com/photo-1619741497312-0e9fb88f5e0f?w=600&h=400&fit=crop",
    calories: 420,
    prepTimeMinutes: 10,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isBestseller: true,
    avgRating: "4.8",
    reviewCount: 51,
    popularityScore: "92.0",
    allergens: ["gluten", "dairy", "nuts"],
  },
  {
    restaurantId: 4,
    nameEn: "Hummus Beiruti",
    nameAr: "حمص بيروتي",
    descriptionEn: "Ultra-smooth chickpea purée drizzled with olive oil and dusted with sumac and cumin — served with warm pita bread.",
    descriptionAr: "بيوريه حمص ناعم جداً مع زيت زيتون وسماق وكمون — يُقدَّم مع خبز البيتا الدافئ.",
    price: "28.00",
    imageUrl: "https://images.unsplash.com/photo-1542528180-1c2803fa048c?w=600&h=400&fit=crop",
    calories: 240,
    prepTimeMinutes: 8,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isHealthy: true,
    avgRating: "4.5",
    reviewCount: 29,
    popularityScore: "83.0",
    allergens: ["gluten", "sesame"],
  },

  // ─── Spice Route (restaurant_id: 5) ─────────────────────────────────────────
  {
    restaurantId: 5,
    nameEn: "Malabar Biryani",
    nameAr: "برياني مالابار",
    descriptionEn: "Slow-cooked dum biryani with Malabar spices, saffron and rosewater, topped with fried pearl onions and a Gulf-style raita.",
    descriptionAr: "برياني دم مطبوخ ببطء بتوابل مالابار والزعفران وماء الورد، مع البصل اللؤلؤي المقلي والريتا الخليجية.",
    price: "95.00",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop",
    calories: 880,
    prepTimeMinutes: 50,
    spiceLevel: 2,
    isHalal: true,
    isBestseller: true,
    isTabaqStar: true,
    avgRating: "4.9",
    reviewCount: 74,
    popularityScore: "96.8",
    allergens: ["dairy"],
  },
  {
    restaurantId: 5,
    nameEn: "Dal Makhani",
    nameAr: "دال ماخاني",
    descriptionEn: "Black lentils slow-cooked overnight in tomato, cream and butter with aromatic whole spices — a north Indian classic.",
    descriptionAr: "عدس أسود مطبوخ طوال الليل ببطء في الطماطم والقشدة والزبدة مع توابل كاملة عطرة — كلاسيكية شمال الهند.",
    price: "48.00",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    calories: 420,
    prepTimeMinutes: 20,
    spiceLevel: 1,
    isHalal: true,
    isVegetarian: true,
    isGlutenFree: true,
    isHealthy: false,
    avgRating: "4.6",
    reviewCount: 39,
    popularityScore: "86.5",
    allergens: ["dairy"],
  },
  {
    restaurantId: 5,
    nameEn: "Lamb Rogan Josh",
    nameAr: "روغان جوش الضأن",
    descriptionEn: "Kashmiri-style slow-braised lamb shanks in a rich red curry of Kashmiri chillies, fennel and whole spices.",
    descriptionAr: "كراع ضأن كشميرية مطهوة ببطء في كاري أحمر غني بالفلفل الكشميري والشمر والتوابل الكاملة.",
    price: "88.00",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    calories: 720,
    prepTimeMinutes: 40,
    spiceLevel: 3,
    isHalal: true,
    isGlutenFree: true,
    isDairyFree: true,
    isChefChoice: true,
    avgRating: "4.8",
    reviewCount: 54,
    popularityScore: "92.2",
    allergens: [],
  },
  {
    restaurantId: 5,
    nameEn: "Arabian Sea Seafood Curry",
    nameAr: "كاري مأكولات بحر العرب",
    descriptionEn: "Fresh Red Sea catch in a coconut-tamarind curry base with turmeric, fenugreek and toasted cumin.",
    descriptionAr: "صيد طازج من البحر الأحمر في قاعدة كاري بجوز الهند والتمر الهندي مع الكركم والحلبة والكمون المحمّص.",
    price: "110.00",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    calories: 580,
    prepTimeMinutes: 30,
    spiceLevel: 2,
    isHalal: true,
    isGlutenFree: true,
    isDairyFree: true,
    isMostOrdered: true,
    avgRating: "4.8",
    reviewCount: 61,
    popularityScore: "93.5",
    allergens: ["fish", "shellfish"],
  },
  {
    restaurantId: 5,
    nameEn: "Garlic Naan",
    nameAr: "نان بالثوم",
    descriptionEn: "Tandoor-baked leavened bread brushed with garlic butter and fresh coriander — the perfect curry companion.",
    descriptionAr: "خبز نان مخمّر مخبوز في التندور ومدهون بزبدة الثوم والكزبرة الطازجة — مرافق الكاري المثالي.",
    price: "14.00",
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop",
    calories: 210,
    prepTimeMinutes: 8,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isMostOrdered: true,
    avgRating: "4.5",
    reviewCount: 82,
    popularityScore: "88.0",
    allergens: ["gluten", "dairy"],
  },
  {
    restaurantId: 5,
    nameEn: "Gulab Jamun",
    nameAr: "غولاب جامون",
    descriptionEn: "Melt-in-the-mouth milk-solid dumplings soaked in a rose and cardamom syrup, garnished with pistachios.",
    descriptionAr: "كرات من مركز الحليب تذوب في الفم، منقوعة في شراب الورد والهيل، مُزيَّنة بالفستق.",
    price: "25.00",
    imageUrl: "https://images.unsplash.com/photo-1590868309235-ea34bed7bd7f?w=600&h=400&fit=crop",
    calories: 360,
    prepTimeMinutes: 10,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isBestseller: true,
    avgRating: "4.7",
    reviewCount: 46,
    popularityScore: "89.5",
    allergens: ["dairy", "nuts"],
  },

  // ─── Al Tazaj (restaurant_id: 6) ────────────────────────────────────────────
  {
    restaurantId: 6,
    nameEn: "Quarter Rotisserie Chicken",
    nameAr: "ربع دجاج روتيسري",
    descriptionEn: "Juicy quarter chicken slow-rotisserie grilled with Al Tazaj's signature 12-spice marinade. Served with garlic sauce and bread.",
    descriptionAr: "ربع دجاج طري مشوي على الشواية البطيئة بتتبيلة توابل التزاج الـ12 الخاصة. يُقدَّم مع صوص الثوم والخبز.",
    price: "28.00",
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=600&h=400&fit=crop",
    calories: 480,
    prepTimeMinutes: 20,
    spiceLevel: 1,
    isHalal: true,
    isMostOrdered: true,
    avgRating: "4.6",
    reviewCount: 95,
    popularityScore: "93.0",
    allergens: [],
  },
  {
    restaurantId: 6,
    nameEn: "Half Rotisserie Chicken",
    nameAr: "نصف دجاج روتيسري",
    descriptionEn: "Half rotisserie chicken with the signature 12-spice marinade, served with two sides of your choice and fresh bread.",
    descriptionAr: "نصف دجاج روتيسري بتتبيلة التوابل الـ12 الخاصة، يُقدَّم مع طبقَي إضافة من اختيارك وخبز طازج.",
    price: "48.00",
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=600&h=400&fit=crop",
    calories: 840,
    prepTimeMinutes: 25,
    spiceLevel: 1,
    isHalal: true,
    isBestseller: true,
    avgRating: "4.7",
    reviewCount: 118,
    popularityScore: "95.5",
    allergens: [],
  },
  {
    restaurantId: 6,
    nameEn: "Chicken Kabsa",
    nameAr: "كبسة دجاج",
    descriptionEn: "Full rotisserie chicken on aromatic kabsa rice cooked in tomato-spice broth with dried lime, bay leaves and black cardamom.",
    descriptionAr: "دجاج روتيسري كامل على أرز كبسة عطر مطبوخ في مرق طماطم متبل مع الليمون الحجري وورق الغار والهيل الأسود.",
    price: "68.00",
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop",
    calories: 1100,
    prepTimeMinutes: 35,
    spiceLevel: 2,
    isHalal: true,
    isChefChoice: true,
    avgRating: "4.8",
    reviewCount: 82,
    popularityScore: "94.8",
    allergens: [],
  },
  {
    restaurantId: 6,
    nameEn: "Chicken Sandwich",
    nameAr: "ساندويش دجاج",
    descriptionEn: "Crispy fried chicken thigh in a brioche bun with coleslaw, pickles and Al Tazaj special sauce.",
    descriptionAr: "فخذ دجاج مقرمش في خبز بريوش مع سلطة الكرنب والمخللات وصوص التزاج الخاص.",
    price: "35.00",
    imageUrl: "https://images.unsplash.com/photo-1582196016295-f8c8bd4b3a99?w=600&h=400&fit=crop",
    calories: 620,
    prepTimeMinutes: 15,
    spiceLevel: 1,
    isHalal: true,
    isNewItem: true,
    isMostOrdered: true,
    avgRating: "4.5",
    reviewCount: 67,
    popularityScore: "88.5",
    allergens: ["gluten", "dairy"],
  },
  {
    restaurantId: 6,
    nameEn: "French Fries",
    nameAr: "بطاطس مقلية",
    descriptionEn: "Crispy golden fries seasoned with sea salt and a light dusting of paprika and cumin.",
    descriptionAr: "بطاطس ذهبية مقرمشة متبلة بملح البحر ورشة خفيفة من الفلفل الحلو والكمون.",
    price: "16.00",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&h=400&fit=crop",
    calories: 350,
    prepTimeMinutes: 10,
    spiceLevel: 1,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isMostOrdered: true,
    avgRating: "4.4",
    reviewCount: 104,
    popularityScore: "87.0",
    allergens: [],
  },
  {
    restaurantId: 6,
    nameEn: "Mixed Garden Salad",
    nameAr: "سلطة خضراء مشكلة",
    descriptionEn: "Fresh chopped salad with romaine, tomato, cucumber, olives and sumac dressing. Light and refreshing.",
    descriptionAr: "سلطة مفرومة طازجة مع الرومان والطماطم والخيار والزيتون وصوص السماق. خفيفة ومنعشة.",
    price: "22.00",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
    calories: 140,
    prepTimeMinutes: 8,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isHealthy: true,
    avgRating: "4.2",
    reviewCount: 41,
    popularityScore: "78.0",
    allergens: [],
  },

  // ─── Nobu (restaurant_id: 7) ─────────────────────────────────────────────────
  {
    restaurantId: 7,
    nameEn: "Yellowtail Jalapeño",
    nameAr: "سمكة الذيل الأصفر بالخلال",
    descriptionEn: "Thinly sliced yellowtail sashimi with sliced jalapeño, ponzu sauce and yuzu zest — Nobu's most iconic creation.",
    descriptionAr: "شرائح رفيعة من ساشيمي الذيل الأصفر مع شرائح الخلال وصوص بونزو وقشر اليوزو — أيقونة نوبو الأشهر.",
    price: "98.00",
    imageUrl: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&h=400&fit=crop",
    calories: 180,
    prepTimeMinutes: 8,
    spiceLevel: 2,
    isHalal: true,
    isDairyFree: true,
    isGlutenFree: true,
    isTabaqStar: true,
    isBestseller: true,
    avgRating: "4.9",
    reviewCount: 89,
    popularityScore: "97.5",
    allergens: ["fish"],
  },
  {
    restaurantId: 7,
    nameEn: "Rock Shrimp Tempura",
    nameAr: "تمبورا الروبيان الصخري",
    descriptionEn: "Crispy rock shrimp in Nobu's signature creamy spicy sauce — a beloved crowd-pleaser since 1994.",
    descriptionAr: "روبيان صخري مقرمش بصوص كريمي حار من ابتكار نوبو — من أحب الأطباق الجماهيرية منذ 1994.",
    price: "115.00",
    imageUrl: "https://images.unsplash.com/photo-1607631568010-a87245c0daf8?w=600&h=400&fit=crop",
    calories: 420,
    prepTimeMinutes: 18,
    spiceLevel: 2,
    isHalal: true,
    isChefChoice: true,
    isMostOrdered: true,
    avgRating: "4.9",
    reviewCount: 102,
    popularityScore: "98.0",
    allergens: ["gluten", "shellfish", "eggs"],
  },
  {
    restaurantId: 7,
    nameEn: "Wagyu Beef Tataki",
    nameAr: "تاتاكي لحم واغيو",
    descriptionEn: "Lightly seared Wagyu A5 beef carpaccio with ponzu, truffle shavings and crispy shallots.",
    descriptionAr: "كاربتشيو لحم واغيو A5 مكوي خفيفاً مع البونزو وشرائح الكمأة والشلوت المقرمش.",
    price: "168.00",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
    calories: 340,
    prepTimeMinutes: 12,
    spiceLevel: 0,
    isHalal: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNewItem: false,
    avgRating: "4.9",
    reviewCount: 55,
    popularityScore: "95.8",
    allergens: ["fish"],
  },
  {
    restaurantId: 7,
    nameEn: "Chilean Sea Bass Den Miso",
    nameAr: "سمك باس التشيلي دن ميسو",
    descriptionEn: "Nobu's legendary sweet miso-marinated Chilean sea bass, broiled to a caramelised golden finish.",
    descriptionAr: "سمك الباس التشيلي المتبل بميسو الحلو الأسطوري من نوبو، مشوي حتى ينضج ذهبياً.",
    price: "228.00",
    imageUrl: "https://images.unsplash.com/photo-1534482421-64566f976cfa?w=600&h=400&fit=crop",
    calories: 490,
    prepTimeMinutes: 25,
    spiceLevel: 0,
    isHalal: true,
    isGlutenFree: false,
    isDairyFree: true,
    isTabaqStar: true,
    avgRating: "5.0",
    reviewCount: 71,
    popularityScore: "99.0",
    allergens: ["fish", "soy"],
  },
  {
    restaurantId: 7,
    nameEn: "King Crab Leg Tempura",
    nameAr: "تمبورا كراب الملك",
    descriptionEn: "Whole king crab leg in a light tempura batter served with karashi mustard soy and toasted sesame.",
    descriptionAr: "ساق سرطان الملك كاملاً بعجينة تمبورا خفيفة مع صوص خردل كاراشي الصويا والسمسم المحمص.",
    price: "175.00",
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&h=400&fit=crop",
    calories: 380,
    prepTimeMinutes: 22,
    spiceLevel: 1,
    isHalal: true,
    isBestseller: true,
    avgRating: "4.8",
    reviewCount: 44,
    popularityScore: "93.0",
    allergens: ["gluten", "shellfish", "sesame"],
  },

  // ─── Karak House (restaurant_id: 8) ─────────────────────────────────────────
  {
    restaurantId: 8,
    nameEn: "Masala Chai",
    nameAr: "شاي ماسالا",
    descriptionEn: "Spiced tea brewed with cinnamon, ginger, cardamom and cloves in full-cream milk — warming and aromatic.",
    descriptionAr: "شاي متبل مغلي بالقرفة والزنجبيل والهيل والقرنفل في حليب كامل الدسم — دافئ وعطر.",
    price: "15.00",
    imageUrl: "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?w=600&h=400&fit=crop",
    calories: 180,
    prepTimeMinutes: 8,
    spiceLevel: 1,
    isHalal: true,
    isVegetarian: true,
    isGlutenFree: true,
    isMostOrdered: true,
    avgRating: "4.7",
    reviewCount: 88,
    popularityScore: "92.0",
    allergens: ["dairy"],
  },
  {
    restaurantId: 8,
    nameEn: "Saffron Karak",
    nameAr: "كرك زعفران",
    descriptionEn: "Premium karak tea infused with Qatari-style saffron strands, rose water and a pinch of cardamom.",
    descriptionAr: "شاي كرك فاخر منقوع بخيوط الزعفران القطري وماء الورد ورشة من الهيل.",
    price: "20.00",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=400&fit=crop",
    calories: 200,
    prepTimeMinutes: 8,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isGlutenFree: true,
    isNewItem: false,
    isTabaqStar: false,
    isBestseller: true,
    avgRating: "4.8",
    reviewCount: 64,
    popularityScore: "91.5",
    allergens: ["dairy"],
  },
  {
    restaurantId: 8,
    nameEn: "Cheese Sambosek",
    nameAr: "سمبوسك جبن",
    descriptionEn: "Crispy fried pastry triangles filled with melted akkawi cheese and nigella seeds — the perfect tea companion.",
    descriptionAr: "مثلثات عجين مقلية مقرمشة محشوة بجبن العكاوي الذائب وحبة البركة — المرافق المثالي للشاي.",
    price: "22.00",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&h=400&fit=crop",
    calories: 280,
    prepTimeMinutes: 10,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isMostOrdered: true,
    avgRating: "4.6",
    reviewCount: 72,
    popularityScore: "89.5",
    allergens: ["gluten", "dairy"],
  },
  {
    restaurantId: 8,
    nameEn: "Zaatar Manakeesh",
    nameAr: "مناقيش زعتر",
    descriptionEn: "Fresh dough flatbread generously spread with a blend of wild thyme, sesame seeds and olive oil, baked until golden.",
    descriptionAr: "خبز عجين طازج ممتد بسخاء بمزيج من الزعتر البري وبذور السمسم وزيت الزيتون، مخبوز حتى يصبح ذهبياً.",
    price: "28.00",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&h=400&fit=crop",
    calories: 320,
    prepTimeMinutes: 15,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isVegan: true,
    isBestseller: true,
    avgRating: "4.6",
    reviewCount: 59,
    popularityScore: "88.0",
    allergens: ["gluten", "sesame"],
  },
  {
    restaurantId: 8,
    nameEn: "Breakfast Eggs & Cheese",
    nameAr: "بيض وجبن للفطور",
    descriptionEn: "Soft scrambled eggs with melted white cheese, fresh tomato and olives, served with warm bread.",
    descriptionAr: "بيض مخفوق ناعم مع جبن أبيض ذائب وطماطم طازجة وزيتون، يُقدَّم مع خبز دافئ.",
    price: "35.00",
    imageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&h=400&fit=crop",
    calories: 380,
    prepTimeMinutes: 12,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    avgRating: "4.5",
    reviewCount: 41,
    popularityScore: "83.0",
    allergens: ["gluten", "dairy", "eggs"],
  },
  {
    restaurantId: 8,
    nameEn: "Chocolate Cake",
    nameAr: "كيكة الشوكولاتة",
    descriptionEn: "Rich moist chocolate cake with a lava-like chocolate ganache centre, served warm with vanilla ice cream.",
    descriptionAr: "كيكة شوكولاتة غنية ورطبة بمركز غاناش شوكولاتة يسيل، تُقدَّم ساخنة مع آيس كريم الفانيليا.",
    price: "28.00",
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop",
    calories: 480,
    prepTimeMinutes: 12,
    spiceLevel: 0,
    isHalal: true,
    isVegetarian: true,
    isBestseller: true,
    avgRating: "4.7",
    reviewCount: 55,
    popularityScore: "90.5",
    allergens: ["gluten", "dairy", "eggs", "nuts"],
  },
];

async function main() {
  console.log("🍽️  Seeding dishes for all restaurants...\n");

  let inserted = 0;
  let skipped = 0;

  for (const dish of DISHES) {
    const existing = await db
      .select({ id: dishesTable.id })
      .from(dishesTable)
      .where(
        // @ts-ignore
        eq(dishesTable.nameEn, dish.nameEn)
      );

    if (existing.length > 0) {
      console.log(`  ⏭️  Skipping "${dish.nameEn}" (already exists)`);
      skipped++;
      continue;
    }

    await db.insert(dishesTable).values({
      restaurantId: dish.restaurantId,
      nameEn: dish.nameEn,
      nameAr: dish.nameAr,
      descriptionEn: dish.descriptionEn,
      descriptionAr: dish.descriptionAr,
      price: dish.price,
      imageUrl: dish.imageUrl ?? null,
      calories: dish.calories ?? null,
      prepTimeMinutes: dish.prepTimeMinutes ?? null,
      spiceLevel: dish.spiceLevel ?? 0,
      isHalal: dish.isHalal ?? false,
      isVegetarian: dish.isVegetarian ?? false,
      isVegan: dish.isVegan ?? false,
      isGlutenFree: dish.isGlutenFree ?? false,
      isDairyFree: dish.isDairyFree ?? false,
      isNutFree: dish.isNutFree ?? false,
      isHealthy: dish.isHealthy ?? false,
      isTabaqStar: dish.isTabaqStar ?? false,
      isBestseller: dish.isBestseller ?? false,
      isChefChoice: dish.isChefChoice ?? false,
      isNewItem: dish.isNewItem ?? false,
      isMostOrdered: dish.isMostOrdered ?? false,
      isAvailable: true,
      avgRating: dish.avgRating ?? "0",
      reviewCount: dish.reviewCount ?? 0,
      popularityScore: dish.popularityScore ?? "0",
      allergens: JSON.stringify(dish.allergens ?? []),
    });

    console.log(`  ✅ [R${dish.restaurantId}] ${dish.nameEn} / ${dish.nameAr} — SAR ${dish.price}`);
    inserted++;
  }

  console.log(`\n✅ Done — ${inserted} inserted, ${skipped} skipped`);
  console.log(`📊 Total dishes in DISHES array: ${DISHES.length}`);

  process.exit(0);
}

main().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
