import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import countriesRouter from "./countries.js";
import categoriesRouter from "./categories.js";
import restaurantsRouter from "./restaurants.js";
import dishesRouter from "./dishes.js";
import menusRouter from "./menus.js";
import bookingsRouter from "./bookings.js";
import offersRouter from "./offers.js";
import campaignsRouter from "./campaigns.js";
import promoCodesRouter from "./promo-codes.js";
import redemptionsRouter from "./redemptions.js";
import reviewsRouter from "./reviews.js";
import usersRouter from "./users.js";
import searchRouter from "./search.js";
import eventsRouter from "./events.js";
import referralsRouter from "./referrals.js";
import usernameRouter from "./username.js";
import adminStatsRouter from "./admin-stats.js";
import adminOffersRouter from "./admin-offers.js";
import adminReferralsRouter from "./admin-referrals.js";
import adminFinanceRouter from "./admin-finance.js";
import addressesRouter from "./addresses.js";
import storiesRouter from "./stories.js";
import partnersRouter from "./partners.js";
import notificationsRouter from "./notifications.js";
import experiencesRouter from "./experiences.js";
import adminExperiencesRouter from "./admin-experiences.js";
import { recommendationsRouter } from "./recommendations.js";
import analyticsRouter from "./analytics.js";
import profileRouter from "./profile.js";
import blogRouter from "./blog.js";
import seoRouter from "./seo.js";
import ordersRouter from "./orders.js";
import disputesRouter from "./disputes.js";
import membershipsRouter from "./memberships.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(countriesRouter);
router.use(categoriesRouter);
router.use(restaurantsRouter);
router.use(dishesRouter);
router.use(menusRouter);
router.use(bookingsRouter);
router.use(offersRouter);
router.use(campaignsRouter);
router.use(promoCodesRouter);
router.use(redemptionsRouter);
router.use(reviewsRouter);
router.use(usersRouter);
router.use(searchRouter);
router.use(eventsRouter);
router.use(referralsRouter);
router.use(usernameRouter);
router.use(adminStatsRouter);
router.use(adminOffersRouter);
router.use(adminReferralsRouter);
router.use(adminFinanceRouter);
router.use(addressesRouter);
router.use(storiesRouter);
router.use(partnersRouter);
router.use(notificationsRouter);
router.use(experiencesRouter);
router.use(adminExperiencesRouter);
router.use(recommendationsRouter);
router.use(analyticsRouter);
router.use(profileRouter);
router.use(blogRouter);
router.use(seoRouter);
router.use(ordersRouter);
router.use(disputesRouter);
router.use(membershipsRouter);

export default router;
