BEGIN;

-- ── Maestro Italian (sections: 10=Starters, 11=Main, 12=Desserts) ─────────────
INSERT INTO dishes (restaurant_id, menu_section_id, name_en, name_ar, description_en, description_ar, price, currency, image_url, is_available, is_halal, is_tabaq_star, is_bestseller, is_most_ordered, is_chef_choice, popularity_score) VALUES
(4, 10, 'Burrata Pugliese', 'بوراتا بولييزي',
 'Fresh burrata on heirloom tomatoes, Sicilian basil oil, and aged balsamic reduction',
 'بوراتا طازجة على طماطم موروثة وزيت الريحان الصقلي وتخفيض البلسميك المعتق',
 89.00, 'SAR', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&q=80',
 true, true, true, true, false, true, 94),
(4, 10, 'Beef Carpaccio', 'كارباتشيو اللحم',
 'Paper-thin Wagyu beef with truffle mayo, parmesan shavings, arugula, and capers',
 'لحم واغيو رفيع مع مايونيز الكمأة والبارميزان والجرجير والكبر',
 95.00, 'SAR', 'https://images.unsplash.com/photo-1544025162-d7669f9f3df4?w=500&q=80',
 true, true, false, true, false, false, 82),
(4, 11, 'Spaghetti Carbonara', 'سباغيتي كاربونارا',
 'Classic Roman carbonara with guanciale, egg yolk, Pecorino Romano, and black pepper',
 'كاربونارا رومانية كلاسيكية مع لحم الخد والصفار وجبنة بيكورينو والفلفل الأسود',
 110.00, 'SAR', 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=500&q=80',
 true, true, true, true, true, false, 97),
(4, 11, 'Risotto Tartufo Nero', 'ريزوتو الكمأة السوداء',
 'Carnaroli rice with Périgord black truffle, Parmigiano-Reggiano, and truffle butter',
 'أرز كارناريولي مع كمأة بيريغور السوداء وبارميجيانو وزبدة الكمأة',
 165.00, 'SAR', 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500&q=80',
 true, true, true, false, false, true, 88),
(4, 12, 'Tiramisu Classico', 'تيراميسو كلاسيكي',
 'Traditional tiramisu with Savoiardi biscuits, mascarpone, espresso, and cocoa',
 'تيراميسو تقليدي مع بسكويت سافويردي والماسكاربوني والإسبريسو والكاكاو',
 65.00, 'SAR', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80',
 true, true, true, true, true, false, 96),
(4, 12, 'Panna Cotta di Vaniglia', 'بانا كوتا الفانيليا',
 'Silky vanilla panna cotta with fresh strawberry coulis and pistachio crumble',
 'بانا كوتا فانيليا ناعمة مع كولي الفراولة الطازجة وفتات الفستق',
 58.00, 'SAR', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&q=80',
 true, true, false, true, false, false, 80);

-- ── Al Baik Express (sections: 13=Starters, 14=Main, 15=Desserts) ─────────────
INSERT INTO dishes (restaurant_id, menu_section_id, name_en, name_ar, description_en, description_ar, price, currency, image_url, is_available, is_halal, is_tabaq_star, is_bestseller, is_most_ordered, is_chef_choice, popularity_score) VALUES
(5, 13, 'Crispy Shrimp Basket', 'سلة الروبيان المقرمشة',
 'Golden crispy shrimp with Al Baik signature cocktail sauce',
 'روبيان مقرمش ذهبي مع صلصة كوكتيل البيك الخاصة',
 28.00, 'SAR', 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=500&q=80',
 true, true, true, true, true, false, 95),
(5, 13, 'Chicken Tenders', 'إصابع الدجاج',
 'Tender white-meat chicken strips with honey mustard dipping sauce',
 'شرائح دجاج طرية من اللحم الأبيض مع صلصة الخردل والعسل',
 22.00, 'SAR', 'https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=500&q=80',
 true, true, false, true, false, false, 88),
(5, 14, 'Broasted Chicken Meal', 'وجبة دجاج مبروست',
 'Full broasted chicken with spicy or garlic sauce, fries, and bread',
 'دجاجة مبروستة كاملة مع صلصة حارة أو ثوم وبطاطس وخبز',
 55.00, 'SAR', 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=500&q=80',
 true, true, true, true, true, false, 99),
(5, 14, 'Family Bucket Feast', 'دلو العائلة',
 '12 pieces mixed broasted chicken, 4 fries, 4 breads, and 4 sauces',
 '12 قطعة دجاج مبروست مشكل، 4 بطاطس، 4 أخبزة و4 صلصات',
 145.00, 'SAR', 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&q=80',
 true, true, true, true, true, false, 98),
(5, 15, 'Date & Honey Cake', 'كيك التمر والعسل',
 'Soft Saudi date cake with honey drizzle and vanilla ice cream',
 'كيك التمر السعودي الطري مع رذاذ العسل وآيس كريم الفانيليا',
 18.00, 'SAR', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80',
 true, true, false, true, false, false, 72);

-- ── Kana Sushi (sections: 16=Starters, 17=Main, 18=Desserts) ─────────────────
INSERT INTO dishes (restaurant_id, menu_section_id, name_en, name_ar, description_en, description_ar, price, currency, image_url, is_available, is_halal, is_tabaq_star, is_bestseller, is_most_ordered, is_chef_choice, popularity_score) VALUES
(6, 16, 'Gyoza Pan-Fried', 'غيوزا مقلية',
 'Handmade pork-free chicken gyoza with yuzu ponzu dipping sauce',
 'غيوزا دجاج مصنوعة يدوياً بدون لحم خنزير مع صلصة يوزو بونزو',
 52.00, 'SAR', 'https://images.unsplash.com/photo-1541696490-8744a5dc0228?w=500&q=80',
 true, true, false, true, false, false, 85),
(6, 16, 'Salmon Tartar', 'تارتار السالمون',
 'Diced sashimi-grade salmon with avocado, sesame oil, and tobiko',
 'سالمون مفروم من درجة الساشيمي مع أفوكادو وزيت السمسم وبيض السمك',
 75.00, 'SAR', 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=500&q=80',
 true, true, true, true, false, true, 90),
(6, 17, 'Dragon Roll', 'رول التنين',
 'Shrimp tempura roll topped with avocado, eel sauce, and sesame',
 'رول روبيان تمبورا مع أفوكادو وصلصة الثعبان والسمسم',
 98.00, 'SAR', 'https://images.unsplash.com/photo-1553621042-f6e14be02cc2?w=500&q=80',
 true, true, true, true, true, false, 96),
(6, 17, 'Salmon Sashimi (8 pcs)', 'ساشيمي سالمون (8 قطع)',
 'Premium Atlantic salmon, hand-cut to order, with wasabi and pickled ginger',
 'سالمون أطلسي مميز يُقطع حسب الطلب مع الوسابي والزنجبيل المخلل',
 115.00, 'SAR', 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=500&q=80',
 true, true, true, false, false, true, 88),
(6, 17, 'Rainbow Roll', 'رول قوس قزح',
 'California roll base topped with assorted sashimi — tuna, salmon, yellowtail',
 'رول كاليفورنيا مع طبقة من الساشيمي المشكلة: تونة وسالمون وذيل أصفر',
 125.00, 'SAR', 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=500&q=80',
 true, true, false, true, false, false, 87),
(6, 18, 'Matcha Lava Cake', 'كيك الماتشا السائل',
 'Warm Japanese matcha chocolate lava cake with yuzu sorbet',
 'كيك الماتشا الياباني الدافئ السائل مع سوربيه اليوزو',
 58.00, 'SAR', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&q=80',
 true, true, true, true, false, false, 89);

-- ── Casa Levant (sections: 22=Starters, 23=Main, 24=Desserts) ────────────────
INSERT INTO dishes (restaurant_id, menu_section_id, name_en, name_ar, description_en, description_ar, price, currency, image_url, is_available, is_halal, is_tabaq_star, is_bestseller, is_most_ordered, is_chef_choice, popularity_score) VALUES
(8, 22, 'Mezze Platter', 'طبق المزة',
 'Hummus, baba ganoush, fattoush, tabbouleh, labneh, olives, and warm Arabic bread',
 'حمص وبابا غنوش وفتوش وتبولة ولبنة وزيتون وخبز عربي دافئ',
 85.00, 'SAR', 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=500&q=80',
 true, true, true, true, true, false, 97),
(8, 22, 'Fatayer Trio', 'فطاير ثلاثية',
 'Handmade pastries filled with spinach & feta, minced lamb, or halloumi & thyme',
 'فطاير محلية الصنع محشوة بالسبانخ والفيتا أو اللحم المفروم أو الحلوم والزعتر',
 55.00, 'SAR', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=80',
 true, true, false, true, false, false, 84),
(8, 23, 'Lamb Ouzi', 'عوزي الضأن',
 'Slow-roasted whole leg of lamb on saffron rice with almonds and pine nuts',
 'فخذ ضأن مشوي ببطء على أرز الزعفران مع اللوز والصنوبر',
 245.00, 'SAR', 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=500&q=80',
 true, true, true, true, false, true, 95),
(8, 23, 'Chicken Musakhan', 'مسخن الدجاج',
 'Roasted chicken on taboon bread with caramelised onion and sumac',
 'دجاج محمر على خبز الطابون مع البصل المكرمل والسماق',
 95.00, 'SAR', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=500&q=80',
 true, true, false, true, true, false, 90),
(8, 24, 'Knafeh bil Jibn', 'كنافة بالجبن',
 'Traditional Palestinian-style knafeh with stretchy cheese, sugar syrup, and pistachio',
 'كنافة فلسطينية تقليدية مع جبنة ممطوطة وقطر وفستق',
 45.00, 'SAR', 'https://images.unsplash.com/photo-1555951015-6da899b5c2cd?w=500&q=80',
 true, true, true, true, true, false, 98);

-- ── Bahar Seafood (sections: 31=Starters, 32=Main, 33=Desserts) ──────────────
INSERT INTO dishes (restaurant_id, menu_section_id, name_en, name_ar, description_en, description_ar, price, currency, image_url, is_available, is_halal, is_tabaq_star, is_bestseller, is_most_ordered, is_chef_choice, popularity_score) VALUES
(11, 31, 'Shrimp Cocktail', 'كوكتيل الروبيان',
 'Chilled tiger prawns with classic cocktail sauce, lemon, and fresh dill',
 'روبيان نمر مبرد مع صلصة الكوكتيل الكلاسيكية والليمون والشبت الطازج',
 75.00, 'SAR', 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=500&q=80',
 true, true, false, true, false, false, 84),
(11, 31, 'Crispy Calamari', 'كالاماري مقرمش',
 'Lightly battered calamari rings with tzatziki and lemon aioli',
 'حلقات كالاماري خفيفة مع تزازيكي وأيولي الليمون',
 68.00, 'SAR', 'https://images.unsplash.com/photo-1558030006-450675393462?w=500&q=80',
 true, true, false, true, true, false, 90),
(11, 32, 'Grilled Hammour Whole', 'هامور مشوي كامل',
 'Whole hammour (Gulf grouper) marinated in za''atar, garlic, and lemon, grilled to perfection',
 'هامور خليجي كامل متبل بالزعتر والثوم والليمون مشوي على أكمل وجه',
 185.00, 'SAR', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&q=80',
 true, true, true, true, true, true, 97),
(11, 32, 'Crab & Shrimp Biryani', 'برياني السرطان والروبيان',
 'Aromatic Gulf-spiced biryani with fresh crab and king prawns',
 'برياني عطر الخليج مع السرطان الطازج والروبيان الملكي',
 145.00, 'SAR', 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=80',
 true, true, true, false, false, false, 88),
(11, 33, 'Umm Ali', 'أم علي',
 'Egyptian bread pudding with puff pastry, nuts, raisins, and sweetened cream',
 'أم علي المصرية مع عجينة الفطير والمكسرات والزبيب والكريمة المحلاة',
 42.00, 'SAR', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80',
 true, true, false, true, false, false, 78);

-- ── Spice Route India (sections: 34=Starters, 35=Main, 36=Desserts) ──────────
INSERT INTO dishes (restaurant_id, menu_section_id, name_en, name_ar, description_en, description_ar, price, currency, image_url, is_available, is_halal, is_tabaq_star, is_bestseller, is_most_ordered, is_chef_choice, popularity_score) VALUES
(12, 34, 'Seekh Kebab', 'سيخ الكباب',
 'Minced lamb seekh kebabs with mint chutney and tandoori-baked naan',
 'كباب السيخ من اللحم المفروم مع صلصة النعناع والنان المخبوز بالتندور',
 72.00, 'SAR', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80',
 true, true, true, true, false, false, 91),
(12, 34, 'Papdi Chaat', 'بابدي تشاات',
 'Crispy flour crisps with chickpeas, tamarind chutney, yogurt, and coriander',
 'بسكويت الدقيق المقرمش مع الحمص وصلصة التمر الهندي والزبادي والكزبرة',
 45.00, 'SAR', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=80',
 true, true, false, true, false, false, 80),
(12, 35, 'Butter Chicken Masala', 'دجاج بالزبدة والمسالا',
 'Slow-cooked tandoor chicken in velvety tomato-butter-cream sauce',
 'دجاج التندور المطهو ببطء في صلصة الطماطم والزبدة والكريمة',
 115.00, 'SAR', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80',
 true, true, true, true, true, true, 98),
(12, 35, 'Dal Makhani', 'دال مخاني',
 'Black lentils slow-cooked overnight with tomato, cream, and buttery spices',
 'عدس أسود مطهو ببطء طوال الليل مع الطماطم والكريمة والتوابل الزبدية',
 75.00, 'SAR', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&q=80',
 true, true, false, true, false, false, 85),
(12, 35, 'Rogan Josh', 'روغان جوش',
 'Kashmiri slow-braised lamb with aromatic spices, yogurt, and fragrant basmati',
 'ضأن كشميري مطهو ببطء مع التوابل والزبادي والأرز البسمتي',
 125.00, 'SAR', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=500&q=80',
 true, true, true, false, false, true, 88),
(12, 36, 'Gulab Jamun', 'غولاب جامون',
 'Soft milk solids dumplings in rose-cardamom syrup, served with saffron ice cream',
 'كرات حليب طرية في شراب الورد والهيل مع آيس كريم الزعفران',
 38.00, 'SAR', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80',
 true, true, true, true, true, false, 93),
(12, 36, 'Kulfi Falooda', 'كولفي فالودة',
 'Traditional Indian kulfi ice cream with rose falooda noodles and basil seeds',
 'آيس كريم كولفي الهندي التقليدي مع نودلز الفالودة ببذور الريحان',
 42.00, 'SAR', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&q=80',
 true, true, false, true, false, false, 82);

COMMIT;

-- Summary verification
SELECT r.name_en, COUNT(d.id) as dish_count
FROM restaurants r
JOIN menus m ON m.restaurant_id = r.id AND m.type = 'food'
JOIN menu_sections ms ON ms.menu_id = m.id
LEFT JOIN dishes d ON d.menu_section_id = ms.id
WHERE r.id IN (4,5,6,8,11,12)
GROUP BY r.id, r.name_en
ORDER BY r.name_en;
